export const introGambleText = [
	"Ah yes, the ‘hope and cope’ method. Bold choice.",
	"Roll for stats? Roll for regrets later.",
	"Let fate decide if you're a hero... or a glorified paperweight.",
	"Your stats are in the hands of RNGesus now. Pray accordingly.",
	"Because spreadsheets are for nerds and chaos is for legends.",
	"This is where dreams are made... or mercilessly crushed.",
	"Welcome to the dice lottery. No refunds.",
	"Min-maxing is for cowards. Let the dice speak truth.",
	"You could be a demigod… or a peasant with a sword. Let’s find out.",
	"Rolling dice: when you want to create a character and trauma.",
	"Live by the dice, die by the dice. Literally.",
	"Who needs balance when you have chaos?",
	"Statistically speaking, this will be a disaster.",
	"Why plan when you can panic?",
	"This is the way. The random way.",
	"Gambling your potential? Strange but I shall allow it",
	"Why min-max when you can just vibe and die at level 2?",
	"Ah yes, the YOLO path. Respect.",
	"In the realm of chance, even a goblin may dream of glory.",
	"By the will of fate, your destiny shall be carved in numbers.",
	"Tread carefully, adventurer... the dice favor no soul.",
	"From chaos comes power... or mediocrity. We shall see.",
	"May the rolls be ever in your favor.",
	"It's dangerous to go alone... Especially with dump stats.",
	"With great rolls comes great responsibility... Maybe.",
	"You either die a hero or live long enough to roll 3 Charisma.",
	"This is the way... of disappointment or domination.",
	"Roll for stats? More like roll for emotional damage.",
	"You ever seen a wizard with 3 Intelligence? You're about to.",
	"Stat generation via ancient dice-based summoning ritual. No guarantees.",
	"Behold: a character born of math crimes and poor life choices.",
	"Your stats have been hexed. Enjoy your cursed gremlin build.",
	"The dice whispered… and I wish they hadn’t.",
	"Something watches as you roll. It hungers for a 1.",
	"You feel a chill. The dice… they know.",
	"This method has consequences. Not rules. Consequences.",
	"Blood was spilled for these stats. Not yours. Yet.",
	"Do you shape your destiny, or does the d6 mock you?",
	"Roll well, or question your existence afterward.",
	"This is your soul in numerical form. Roll wisely.",
	"Hope is a fragile thing. Just like your Strength stat.",
	"Life is random. So are your stats. Coincidence? I think not.",
	"No RNG protection here. Welcome to the skill issue zone.",
	"Let’s see if your build gets nerfed at birth.",
	"Rolling dice like it’s loot box season.",
	"Rolling stats is a high-risk, high-regret solution.",
	"Think outside the spreadsheet... embrace agile diceflow.",
	"Your character’s KPIs have been outsourced to fate.",
	"Per our last session, the dice are now in charge.",
];

export const explanationGambleText = [
	"Choose the number of dice you want to roll and discard for each stat.",
];

export const goodGambleText = [
	"Rolling good is a skill after all.",
	"I pray you get a nat 1 immediately.",
	"You either cheated, or you're chosen by the dice gods.",
	"Be honest: you made a deal with something, didn't you?",
	"Congratulations, you're now legally a main character.",
	"Woah, main character alert",
	"With stats like that, even your backstory writes itself.",
	"That roll slaps harder than a bard with max Charisma.",
	"Legend says these numbers echo through the planes.",
	"Statistically illegal. Morally inspiring.",
	"Your dice are sweating from exertion. Well done.",
	"Your DM is not going to like this.",
	"Bro just unlocked godmode in a tabletop game.",
	"The party's new tank, DPS, AND emotional support NPC.",
	"Your Honor, this player is cracked.",
	"Go ahead. Roll Intimidation. The dice are scared of you.",
	"That’s the kind of roll that inspires a tavern ballad.",
	"Sweet rolls, sweet soul, sweet chaos ahead.",
	"You just made a statline so beautiful I might cry.",
	"Legends will be written, mostly by me, with flair.",
	"If fate were a dance, you just nailed the performance.",
	"Truly a hero in the making... or at least a very smug one.",
	"With stats like that, the bards won’t shut up about you.",
	"That’s not a roll, that’s a divine blessing in disguise.",
];

export const badGambleText = [
	"AHAHAHAHA... I mean that's too bad",
	"Unlucky kid. Maybe the DM will be nicer to you...",
	"LMAO",
	"Have you considered another hobby?",
	"Time to roleplay emotional resilience.",
	"You've been chosen… as comic relief.",
	"Stat spread sponsored by tragedy and tears.",
	"Congrats! You rolled a sentient potato.",
	"Your sheet just failed a vibe check.",
	"At least you’ll have a great personality. Maybe.",
	"You're not a glass cannon. You're just glass.",
	"Roll up a backup character now. Just in case.",
	"This isn’t a stat block. It’s a cry for help.",
	"You could be useful… as bait.",
	"Oh no... oh yes.",
	"Those stats bring me joy... and you despair.",
	"Perfect, now I don’t have to balance anything.",
	"The monsters thank you in advance.",
	"Your suffering is the real campaign reward.",
	"You’re not underpowered, you’re narratively interesting.",
	"I smell a tragic backstory incoming.",
	"Excellent, I love my characters squishy and full of fear.",
	"Rolling this bad should come with a waiver.",
	"I promise I won’t exploit this... probably.",
];

export const midGambleText = [
	"Wow, you rolled mid. Just like your future journey.",
	"A truly average hero for truly average times.",
	"Could be worse. Could be inspiring. It's neither.",
	"This build screams ‘background NPC with dreams.’",
	"Perfectly balanced, as all mid-tier things should be.",
	"You are the embodiment of 'meh'.",
	"Not bad, not great — just a stat smoothie.",
	"Middle of the road, baby. Safe, forgettable, reliable.",
	"Your stats are... statistically plausible.",
	"The dice have spoken: you're painfully okay.",
	"You're the sidekick with main character ambitions.",
	"You're built like an alignment chart: conflicted.",
	"Decent rolls. You've got 'town guard #3' energy.",
	"The party won’t hate you, but they won’t remember you either.",
	"Your stat sheet is the emotional equivalent of dry toast.",
	"Mediocrity has never looked so... playable.",
	"Like oatmeal, but adventuring.",
	"An excellent foundation for deeply average decisions.",
	"Those rolls scream 'I survive... barely'.",
	"Neither cursed nor blessed, just mildly inconvenienced.",
	"I’ll compose a ballad titled ‘Eh’ in your honor.",
	"You're not doomed, just narratively flexible.",
	"Inspiringly uninspired.",
	"Perfectly acceptable, in the most forgettable way.",
];
