export const introGambleText = [
	"Ah yes, the ‘hope and cope’ method. Bold choice.",
	"Roll for stats? Roll for regrets later.",
	"Let fate decide if you're a hero... or a glorified paperweight.",
	"Your stats are in the hands of RNGesus now. Pray accordingly.",
	"Because spreadsheets are for nerds and chaos is for legends.",
	"This is where dreams are made... or mercilessly crushed.",
	"Welcome to the dice lottery. No refunds.",
	"Min-maxing is for cowards. Let the dice speak truth.",
	"You could be a demigod… or a peasant with a sword. Let’s find out.",
	"Rolling dice: when you want to create a character and trauma.",
	"Live by the dice, die by the dice. Literally.",
	"Who needs balance when you have chaos?",
	"Statistically speaking, this will be a disaster.",
	"Why plan when you can panic?",
	"This is the way. The random way.",
	"Gambling your potential? Strange but I shall allow it",
	"Why min-max when you can just vibe and die at level 2?",
	"Ah yes, the YOLO path. Respect.",
	"In the realm of chance, even a goblin may dream of glory.",
	"By the will of fate, your destiny shall be carved in numbers.",
	"Tread carefully, adventurer... the dice favor no soul.",
	"From chaos comes power... or mediocrity. We shall see.",
	"May the rolls be ever in your favor.",
	"It's dangerous to go alone... Especially with dump stats.",
	"With great rolls comes great responsibility... Maybe.",
	"You either die a hero or live long enough to roll 3 Charisma.",
	"This is the way... of disappointment or domination.",
	"Roll for stats? More like roll for emotional damage.",
	"You ever seen a wizard with 3 Intelligence? You're about to.",
	"Stat generation via ancient dice-based summoning ritual. No guarantees.",
	"Behold: a character born of math crimes and poor life choices.",
	"Your stats have been hexed. Enjoy your cursed gremlin build.",
	"The dice whispered… and I wish they hadn’t.",
	"Something watches as you roll. It hungers for a 1.",
	"You feel a chill. The dice… they know.",
	"This method has consequences. Not rules. Consequences.",
	"Blood was spilled for these stats. Not yours. Yet.",
	"Do you shape your destiny, or does the d6 mock you?",
	"Roll well, or question your existence afterward.",
	"This is your soul in numerical form. Roll wisely.",
	"Hope is a fragile thing. Just like your Strength stat.",
	"Life is random. So are your stats. Coincidence? I think not.",
	"No RNG protection here. Welcome to the skill issue zone.",
	"Let’s see if your build gets nerfed at birth.",
	"Rolling dice like it’s loot box season.",
	"Rolling stats is a high-risk, high-regret solution.",
	"Think outside the spreadsheet... embrace agile diceflow.",
	"Your character’s KPIs have been outsourced to fate.",
	"Per our last session, the dice are now in charge.",
];

export const explanationGambleText = [
	"Choose the number of dice you want to roll and discard for each stat.",
];

export const goodGambleText = [
	"Rolling good is a skill after all.",
	"I pray you get a nat 1 immediately.",
	"You either cheated, or you're chosen by the dice gods.",
	"Be honest: you made a deal with something, didn't you?",
	"Congratulations, you're now legally a main character.",
	"Woah, main character alert",
	"With stats like that, even your backstory writes itself.",
	"That roll slaps harder than a bard with max Charisma.",
	"Legend says these numbers echo through the planes.",
	"Statistically illegal. Morally inspiring.",
	"Your dice are sweating from exertion. Well done.",
	"Your DM is not going to like this.",
	"Bro just unlocked godmode in a tabletop game.",
	"The party's new tank, DPS, AND emotional support NPC.",
	"Your Honor, this player is cracked.",
	"Go ahead. Roll Intimidation. The dice are scared of you.",
	"That’s the kind of roll that inspires a tavern ballad.",
	"Sweet rolls, sweet soul, sweet chaos ahead.",
	"You just made a statline so beautiful I might cry.",
	"Legends will be written, mostly by me, with flair.",
	"If fate were a dance, you just nailed the performance.",
	"Truly a hero in the making... or at least a very smug one.",
	"With stats like that, the bards won’t shut up about you.",
	"That’s not a roll, that’s a divine blessing in disguise.",
	"Statistically speaking, you're a one-in-a-million headache for your DM.",
	"You just got chosen for plot armor. Use it wisely.",
	"That stat block could win elections in three kingdoms.",
	"Your dice didn’t roll, they flexed.",
	"DMs fear you, goblins envy you.",
	"That’s the kind of spread that gets you adopted by dragons.",
	"You just skipped character arc and went straight to legend.",
	"Even the gods rolled their eyes. Jealously.",
	"I can hear the loot calling your name already.",
	"If this were a video game, you'd be patched by morning.",
	"You're not OP... you're just narratively gifted.",
	"That's not min-maxing, that's max-maxing.",
	"You didn’t roll stats, you summoned destiny.",
	"With numbers like these, even the lich wants to party with you.",
	"You're going to make every encounter look like a tutorial.",
	"Power like this belongs in a glass case.",
	"You just made a cleric question their god.",
	"Whatever you’re cooking, it’s well-seasoned and overpowered.",
	"That’s not a dump stat... that’s luxury stat allocation.",
	"The dice just gave you their blessing and their firstborn.",
	"You rolled so well, the table went silent out of respect.",
	"Honestly? You’re the final boss now.",
	"Your numbers are causing local time distortions.",
	"This roll's so hot, I’m surprised it didn’t catch fire.",
];

export const badGambleText = [
	"AHAHAHAHA... I mean that's too bad",
	"Unlucky kid. Maybe the DM will be nicer to you...",
	"LMAO",
	"Have you considered another hobby?",
	"Time to roleplay emotional resilience.",
	"You've been chosen… as comic relief.",
	"Stat spread sponsored by tragedy and tears.",
	"Congrats! You rolled a sentient potato.",
	"Your sheet just failed a vibe check.",
	"At least you’ll have a great personality. Maybe.",
	"You're not a glass cannon. You're just glass.",
	"Roll up a backup character now. Just in case.",
	"This isn’t a stat block. It’s a cry for help.",
	"You could be useful… as bait.",
	"Oh no... oh yes.",
	"Those stats bring me joy... and you despair.",
	"Perfect, now I don’t have to balance anything.",
	"The monsters thank you in advance.",
	"Your suffering is the real campaign reward.",
	"You’re not underpowered, you’re narratively interesting.",
	"I smell a tragic backstory incoming.",
	"Excellent, I love my characters squishy and full of fear.",
	"Rolling this bad should come with a waiver.",
	"I promise I won’t exploit this... probably.",
	"That roll triggered a local tragedy.",
	"Statistically impressive... in the worst way.",
	"You've unlocked the rare 'sad trombone' achievement.",
	"I'm framing this and hanging it in the Hall of Regret.",
	"If dice could apologize, yours would.",
	"You didn’t roll stats, you summoned pity.",
	"You'll be remembered... mostly for this moment.",
	"The party will use you for emotional support and traps.",
	"Your numbers are eligible for medieval worker’s comp.",
	"Even the goblins feel bad for you.",
	"You’re basically an NPC’s understudy now.",
	"Hope you like roleplaying ‘scrappy underdog’.",
	"With rolls like this, you’ll definitely develop character.",
	"Did you insult the dice beforehand or something?",
	"This sheet reads like a warning label.",
	"Welcome to Dungeons & Disappointments.",
	"I’d help, but this is just funny now.",
	"Put those numbers on a mug labeled 'try again'.",
	"You're gonna bond real hard with the floor.",
	"I’m not mad. I’m impressed. But still sad.",
	"This build is less glass cannon, more wet paper sword.",
	"The only thing you'll be killing is party morale.",
	"At least your funeral will be well-written.",
];

export const midGambleText = [
	"Wow, you rolled mid. Just like your future journey.",
	"A truly average hero for truly average times.",
	"Could be worse. Could be inspiring. It's neither.",
	"This build screams ‘background NPC with dreams.’",
	"Perfectly balanced, as all mid-tier things should be.",
	"You are the embodiment of 'meh'.",
	"Not bad, not great... just a stat smoothie.",
	"Middle of the road, baby. Safe, forgettable, reliable.",
	"Your stats are... statistically plausible.",
	"The dice have spoken: you're painfully okay.",
	"You're the sidekick with main character ambitions.",
	"You're built like an alignment chart: conflicted.",
	"Decent rolls. You've got 'town guard #3' energy.",
	"The party won’t hate you, but they won’t remember you either.",
	"Your stat sheet is the emotional equivalent of dry toast.",
	"Mediocrity has never looked so... playable.",
	"Like oatmeal, but adventuring.",
	"An excellent foundation for deeply average decisions.",
	"Those rolls scream 'I survive... barely'.",
	"Neither cursed nor blessed, just mildly inconvenienced.",
	"I’ll compose a ballad titled ‘Eh’ in your honor.",
	"You're not doomed, just narratively flexible.",
	"Inspiringly uninspired.",
	"Perfectly acceptable, in the most forgettable way.",
	'Your stats walked the line between "meh" and "eh."',
	"A perfect fit for side quests no one remembers.",
	"Not weak enough to be funny, not strong enough to be useful.",
	"If your stats were soup, they’d be lukewarm and beige.",
	"You're not built to win... you're built to participate.",
	"These numbers are the human equivalent of a shrug.",
	"A reliable build for unreliable results.",
	"Your character arc is gonna rely heavily on luck.",
	"The most exciting thing here is how unexciting it is.",
	"I’ve seen porridge with more personality.",
	'Even the dice were like "sure, whatever".',
	"You’re basically the median adventurer.",
	"The definition of 'fine, I guess'.",
	"A statline so neutral, it skipped alignment entirely.",
	"If consistency was a flavor, you'd be room temperature water.",
	"The tavern bard paused, unsure if this was worth singing about.",
	"You're not a power fantasy... you're a mild suggestion.",
	'You’re giving strong "NPC who survives the invasion" energy.',
	"This is the kind of roll that makes enemies underestimate you... and still win.",
	"Perfectly suitable for filling the last chair at the table.",
	"I've seen more edge in a dinner roll.",
	"Welcome to the middle lane of destiny.",
	"You won’t die fast... but you won’t live memorably.",
	"These stats are like air... necessary, invisible, unremarkable.",
];

export const duplicateGambleText = [
	"Okay what... how did you even do that?",
	"Six of the same? Are you summoning something?",
	"That’s either divine intervention or an RNG glitch.",
	"I’m not saying you cheated, but the dice are staring at me weird now.",
	"Statistically impossible... narratively hilarious.",
	"That’s not a character, that’s a cursed artifact.",
	"You just unlocked a new form of cosmic symmetry.",
	"The dice have spoken. And apparently, they only speak one number.",
	"Was that planned, or did the algorithm just gain sentience?",
	"Even the gods are confused. And a little scared.",
	"Well... you certainly made a choice. Or fate did.",
	"Okay, no one breathe. We may have just witnessed a prophecy.",
	"I’m sorry, are you trying to ascend to myth tier?",
	"You’ve broken math and possibly reality. Nice.",
	"That number owns you now. It’s your whole personality.",
];

export const highSTDGambleText = [
	"Whoa... you're either a prodigy or a liability.",
	"That statline is screaming, and I can’t tell if it’s joy or pain.",
	"You’ve got hero energy... and sidekick weaknesses.",
	"Peak and pit in the same sheet. Bold.",
	"I see you chose chaos as your dump stat.",
	"You're either going to save the day or trip over a squirrel.",
	"Rolls like this make DMs sweat and players dream.",
	"A masterpiece of imbalance. I respect it.",
	"This character has range... emotionally and statistically.",
	"You min-maxed by accident, didn’t you?",
	"That’s not a build, that’s a rollercoaster.",
	"You’re either carried by fate or dragged by dice.",
	"Half of you could lead an army. The other half... shouldn’t.",
	"One stat slaps, the other apologizes for it.",
	"Your dice were clearly arguing mid-roll.",
	"Oh yes, now *that’s* a character with flavor!",
	"Legends aren’t balanced, they’re memorable!",
	"I shall sing of your greatness... and your very silly flaws.",
	"You’ve got the heart of a lion and the reflexes of a falling rock!",
	"Your strengths will shine, your weaknesses will get comic relief.",
	"This is what real heroes are made of — extremes and backstories!",
	"A build like this demands a ballad... or maybe a rock opera.",
	"Your flaws give your strengths more punch — it’s called drama!",
	"An unbalanced statline? More like personality in numeric form.",
	"You’ve got range, darling. Absolute narrative range.",
	"Oh yes, now that’s a character with flavor!",
	"Legends aren’t balanced, they’re memorable!",
	"I shall sing of your greatness... and your very silly flaws.",
	"You’ve got the heart of a lion and the reflexes of a falling rock!",
	"Your strengths will shine, your weaknesses will get comic relief.",
	"This is what real heroes are made of... extremes and backstories!",
	"A build like this demands a ballad... or maybe a rock opera.",
	"Your flaws give your strengths more punch... it’s called drama!",
	"An unbalanced statline? More like personality in numeric form.",
	"You’ve got range, darling. Absolute narrative range.",
	"This is the DnD equivalent of a spicy burrito.",
	"Your stats look like they were rolled during an earthquake.",
	"One stat’s a king, the other’s a court jester.",
	"I see you’re cosplaying as a competent disaster.",
	"You’re one nat 20 from glory and one nat 1 from memes.",
	"Congrats, you’re both gifted and cursed!",
	"This build is giving 'I lift with my brain' energy.",
	"Basically a superhero with a caffeine allergy.",
	"Half of you can take on a dragon, the other half can't open a door.",
	"This is peak roleplay potential and peak party liability.",
	"I hope you like getting advantage... and also hitting zero HP often.",
	"So we’re min-maxing unintentionally now? Awesome.",
];
