export const lowStr = [
	`Whoever's stats you uploaded skipped arm day forever.`,
	`This looks less like a strength score and more like a cry for help.`,
	`You hit "upload" and the server laughed.`,
	`Clearly you stole the stats of someone allergic to lifting.`,
	`This is what happens when you copy a bard who only lifts morale.`,
	`The original owner used this strength to lift nothing but spirits.`,
	`You uploaded stats and inherited noodle limbs.`,
	`Even the barbarian looked at this and said "not my kind of weak."`,
	`The weight limit is one regret.`,
	`Someone clearly dumped all their points into interpretive dance instead.`,
	`Uploaded from a realm where strength is considered impolite.`,
	`This stat feels like it was left in the sun too long.`,
	`The original user survived using wit, not weights.`,
	`It's a miracle you can carry a character sheet, let alone gear.`,
	`Strength like this should come with a waiver form.`,
	`You clicked "upload" and gravity doubled.`,
	`The forge refused to acknowledge your existence.`,
	`Those muscles are mostly decorative.`,
	`Even the dice look disappointed.`,
	`You now legally qualify as a strong breeze hazard.`,
	`The muscles were optional, and the upload skipped them entirely.`,
	`You make a mimic feel swole.`,
	`Stat review: flagged for structural instability.`,
	`Even your footsteps feel apologetic.`,
	`The sword refused to attune out of pity.`,
	`Your backpack now doubles as a body bag.`,
	`Concerned note from the paladin: "Do you need help with stairs?"`,
	`Strength check failed. On standing.`,
	`The last time you punched, it healed the enemy emotionally.`,
	`You uploaded someone's stats and got their lifelong noodle arms.`,
	`The guild sent a letter saying "thank you for not applying."`,
	`Your climbing speed is technically negative.`,
	`Fantasy OSHA says you're not cleared for lifting anything heavier than a dagger.`,
	`These stats were returned to sender, but you're still holding them.`,
	`The only thing you wrestle is shame.`,
];
export const lowInt = [
	`You uploaded someone's stats and got their dial-up brain.`,
	`This intellect was borrowed from someone banned from riddles.`,
	`You got the stats of a wizard's assistant who kept mixing potions with soup.`,
	`These thoughts come pre-scattered.`,
	`The brain you uploaded runs on scrolls and daydreams.`,
	`You're now the proud owner of thoughts that occasionally wander off.`,
	`Clearly the original user thought "smart is for nerds."`,
	`You uploaded a stat block and downloaded confusion.`,
	`This intellect came with a warning label and you ignored it.`,
	`If this was a software update, you installed the beta version by accident.`,
	`It's less about what you know and more about how loudly you guess.`,
	`This brain once lost an argument to a rock.`,
	`The previous owner majored in interpretive thinking.`,
	`Your logic has the consistency of melted cheese.`,
	`The upload came with 1 idea and it's already expired.`,
	`Critical thinking left the chat.`,
	`Whoever made these choices had a lot of confidence and no facts.`,
	`You now think in vibes and grainy flashbacks.`,
	`The mind palace is under renovation and staffed by pigeons.`,
	`You uploaded someone's stats and received their midterms. Unfinished.`,
	`Whoever owned this brain ran on instinct and bad assumptions.`,
	`Every idea needs a co-signer.`,
	`You uploaded an intellect and it came with malware.`,
	`Fantasy HR flagged your cognition for "under review."`,
	`This level of insight gets you lost in one-room dungeons.`,
	`You're the party's mystery. Not the solver.`,
	`Your mind palace is built entirely out of popsicle sticks.`,
	`Thinking requires concentration. You have neither.`,
	`Even the warlock stopped explaining things to you.`,
	`You once asked the lich what a "skeleton" was.`,
	`Your ideas arrive by carrier pigeon. Lost ones.`,
	`Uploaded a brain. Got soup.`,
	`The wizard handed you a book. You used it as a plate.`,
	`This mental capacity was left behind at a tavern.`,
	`Party note: Stop trying to decipher maps. Please.`,
];
export const lowDex = [
	`This character moves like their bones are made of apologetic pudding.`,
	`Uploaded someone's stats and now doors are your nemesis.`,
	`You inherited the grace of someone who was banned from hopscotch.`,
	`Whoever these belong to tried parkour and got sued by gravity.`,
	`Stealth is now legally classified as a comedy routine.`,
	`This dexterity came from a person who tripped over a carpet square.`,
	`Agility levels: spilled yogurt.`,
	`These reflexes are best described as hopeful.`,
	`You uploaded a rogue's evil twin's stats.`,
	`Every combat round is now a slapstick sketch.`,
	`The only thing quick about you is how fast you fall.`,
	`The original owner moved like a sleep-deprived giraffe.`,
	`If this were a video game, you'd be stuck on the tutorial forever.`,
	`Even your shadow walks into walls.`,
	`Uploaded a stat sheet, downloaded buttered limbs.`,
	`You dodge like someone whose feet were installed wrong.`,
	`Your footsteps now include a musical number.`,
	`Every surface is now difficult terrain out of fear.`,
	`This dexterity was last seen trying to climb out of a well.`,
	`You move with the urgency of a wet sock race.`,
	`The upload came with extra noise and zero control.`,
	`This body moves like it's buffering.`,
	`You have all the subtlety of a bard falling down stairs.`,
	`Your idea of stealth is turning the lights off.`,
	`Whoever uploaded this had an allergy to balance.`,
	`Your reflexes are just social anxiety.`,
	`Fantasy HR suggests avoiding tightropes and open terrain.`,
	`You fall so often the ground filed a restraining order.`,
	`The rogue gave you "the look." You know the one.`,
	`Your default position is prone.`,
	`The upload came with mandatory fumbles.`,
	`Initiative rolls politely ignore you.`,
	`You once tripped and took fall damage in a cutscene.`,
	`The only thing agile is your regret.`,
	`You move like the dice rolled out of the box and under the couch.`,
];
export const lowCon = [
	`Uploaded someone else's stats and caught the flu in the process.`,
	`These hit points arrive pre-dented.`,
	`You now sneeze in initiative order.`,
	`The original owner once lost a duel to pollen.`,
	`Someone else's bad choices are now in your bloodstream.`,
	`This constitution came with seasonal weaknesses.`,
	`Armor? No. You wear regret.`,
	`Every breath is a skill challenge.`,
	`You now take damage from strong emotions.`,
	`Uploaded a stat sheet, caught a disease.`,
	`You pass out if someone mentions battle.`,
	`This level of health should be under quarantine.`,
	`The cleric rolled their eyes before you even said hello.`,
	`Even potions give up halfway through.`,
	`This body runs on expired trail mix.`,
	`Resting only slightly delays your collapse.`,
	`Random upload complete. Constitution not found.`,
	`Whoever owned this before only fought existential dread.`,
	`Your HP bar has a sarcastic tooltip.`,
	`The next strong breeze might end your arc.`,
	`These stats came with a cough and existential dread.`,
	`The upload form mentioned "fragile" in bold.`,
	`Your veins run on potion fumes and sheer will.`,
	`You've failed more saving throws than you've taken.`,
	`Even health potions sigh when they see you.`,
	`The DM has a folder labeled "just in case you fall again."`,
	`Climbing stairs now requires a Constitution check.`,
	`You're one sneeze away from a side quest in the afterlife.`,
	`The necromancer called and asked if you're available soon.`,
	`Fantasy HR advises limiting exposure to anything.`,
	`The original owner only survived via plot armor.`,
	`You were uploaded at 2 HP and a dream.`,
	`You're the reason the cleric now has stress-induced healing.`,
	`Your blood type is "glass."`,
	`The wizard uses Mage Hand to hold you upright.`,
];
export const lowWis = [
	`You uploaded the judgment of a squirrel chasing fireworks.`,
	`This stat sheet has "trusted the wrong wizard" energy.`,
	`The instincts of a fantasy NPC with no backstory.`,
	`You now think with your eyes closed.`,
	`The original owner made choices. Bad ones.`,
	`You uploaded someone else's experience and got none of it.`,
	`You now believe in signs. All of them. Simultaneously.`,
	`This stat came with poor life decisions preinstalled.`,
	`Even your dreams give bad advice.`,
	`Now licensed to ignore red flags.`,
	`The druid said "you're not ready for nature."`,
	`Insight checks have become horror stories.`,
	`Every hunch is an unqualified guess.`,
	`The gods are trying to send messages. You're on mute.`,
	`You ask questions no one wants to hear.`,
	`The forest whispers to you. You don't listen.`,
	`The original owner was legally blind to context.`,
	`Uploaded wisdom. Received hubris.`,
	`Even fortune cookies side-eye you.`,
	`You would follow a siren into accounting.`,
	`Uploaded someone's instincts and got their worst ideas.`,
	`You have the situational awareness of a damp curtain.`,
	`Whoever these stats belonged to trusted far too many weird mushrooms.`,
	`Every insight check starts with a sigh and ends in confusion.`,
	`You once failed a perception check on your own name.`,
	`Fantasy HR suggests basic re-training. And adult supervision.`,
	`The druid said you "radiate poor forest choices."`,
	`The only thing you sense is regret approaching.`,
	`Your last survival tactic was "hug the owlbear."`,
	`You're now the team's moral compass. It's broken.`,
	`Your gut instinct comes with a built-in delay.`,
	`Uploaded wisdom and it immediately asked for directions.`,
	`You hear whispers from the gods. They sound disappointed.`,
	`Your instincts are still buffering.`,
	`Every red flag looks like a welcome banner.`,
];
export const lowCha = [
	`The person you copied was voted "most likely to ruin a first impression."`,
	`This charisma stat smells like it's been left in the sun.`,
	`Uploaded someone else's charm and got whatever this is.`,
	`Even illusions refuse to look like you.`,
	`The bard cried. Not from laughter.`,
	`Your voice has the tone of a wet broom.`,
	`This stat sheet came from the king of awkward pauses.`,
	`NPCs consider you part of the background.`,
	`You uploaded someone's stats and now town guards follow you out of pity.`,
	`Persuasion checks result in doors slamming themselves.`,
	`Your aura is best described as "customer complaint."`,
	`This is the charisma of someone who got kicked out of a mime troupe.`,
	`The tavern cleared out before you even entered.`,
	`Uploaded charm, received static shock.`,
	`This face could stop a negotiation.`,
	`You once told a story so poorly the listener took psychic damage.`,
	`Charisma this low is a recognized medical condition.`,
	`Even the mirror refuses to make eye contact.`,
	`Your smile is now a debuff.`,
	`The party asked you to stay quiet. During downtime.`,
	`This upload came with a legally binding social awkwardness.`,
	`Your charisma score has its own NDA.`,
	`The original owner once got kicked out of a mime guild.`,
	`NPCs refer to you as "that one" with a wince.`,
	`Your face is the leading cause of persuasion failures.`,
	`Uploaded charm and the server flagged it for low quality.`,
	`Fantasy HR suggests silence and large hats.`,
	`You once insulted someone with a compliment.`,
	`The bard replaced your dialogue with interpretive humming.`,
	`The king's court voted to ignore you preemptively.`,
	`Your presence is like a bad smell in a polite room.`,
	`Even illusions give you a charisma penalty.`,
	`You were uploaded with a charisma score and zero social warranty.`,
	`The local tavern has a seat labeled "please no."`,
	`You cast Suggestion and they left the continent.`,
];
export const highStr = [
	`Who did you upload, Hercules?`,
	`You picked stats and the gym exploded.`,
	`Even the barbarian said "yo chill."`,
	`This strength score feels illegal in three realms.`,
	`You uploaded a war god's shoulder day and called it a character.`,
	`NPCs ask if they can be carried. Literally.`,
	`Fantasy HR called to confirm this wasn't a joke.`,
	`Every weapon you touch gets a little afraid.`,
	`Uploaded stats and got an arm-wrestling legend.`,
	`You are now a blunt force trauma subclass.`,
	`The party uses you as a siege weapon.`,
	`Even your flex checks pass.`,
	`"Break the door?" No, you broke the house.`,
	`Uploaded strength, downloaded a lawsuit.`,
	`You just passed a Strength check to open a locked soul.`,
	`This kind of stat should come with cooldowns.`,
	`You flexed and a monk reached enlightenment.`,
	`Even dragons check your biceps before fighting.`,
	`The DM looked at your roll and started drinking.`,
	`Your strength modifier has its own fan club.`,
	`The sword didn't choose the wielder, it filed for protection.`,
	`This much muscle should require a license.`,
	`DM whispered "oh no" when your sheet loaded.`,
	`Lifting the plot? Done.`,
	`Your handshake rolls for damage.`,
	`The ground takes psychic damage when you jump.`,
	`Uploaded stats and gravity filed a complaint.`,
	`The monk tried to spar. We don't talk about what happened.`,
	`Every Strength check is just a flex confirmation.`,
	`The barbarian avoids eye contact now.`,
];
export const highInt = [
	`Uploaded someone's stats and accidentally became a spell theory professor.`,
	`You now calculate spell trajectories mid-fight while solving sudoku.`,
	`This intelligence comes with citations.`,
	`You know 14 languages and roast people in all of them.`,
	`Even the wizard asked if you're hiring.`,
	`You rolled arcana and discovered a new school of magic.`,
	`Uploaded intellect. Now you have office hours.`,
	`The DM is googling how to challenge you.`,
	`Your brain has side quests.`,
	`You cast Identify using eye contact.`,
	`Even the lich is impressed. And scared.`,
	`You're not thinking ahead. You're thinking three timelines ahead.`,
	`Uploaded someone's mind and now you're the lore.`,
	`Fantasy HR filed your brain under "too smart to die."`,
	`You created a theory during a fireball.`,
	`You've become the wizard's final exam.`,
	`Your ideas have footnotes.`,
	`Even riddles say "never mind" when you're near.`,
	`You're now legally able to teach at the arcane university.`,
	`The party just asks "What do you think?" and does that.`,
	`The spellbook read you and leveled up.`,
	`Intelligence this high needs its own server.`,
	`Every plan has a contingency. Even the jokes.`,
	`DM gave up hiding puzzles. You autocompleted them.`,
	`This brain operates on patch notes.`,
	`Arcane libraries subscribe to your thoughts.`,
	`You invented a cantrip mid-combat. It's canon now.`,
	`Your thoughts roll with advantage against confusion.`,
	`The wizard asked if you're from the future.`,
	`Reality sometimes consults you for consistency.`,
];
export const highDex = [
	`Uploaded someone's stats and now you're sponsored by gravity.`,
	`You dodge so smoothly it's considered art.`,
	`This agility is a flex and a threat.`,
	`Even traps start to apologize.`,
	`You move like the DM's frame rate dropped.`,
	`Uploaded a rogue. Got a blur.`,
	`Stealth is not a roll, it's a lifestyle.`,
	`Your steps don't even make narrative noise.`,
	`The monk asked for tips.`,
	`You're so fast you triggered a time loop.`,
	`This dexterity is just speedrunning the universe.`,
	`The rogue has accepted their retirement.`,
	`The enemy missed you in real life.`,
	`Uploaded mobility. Unlocked main character privileges.`,
	`You passed an Acrobatics check by blinking.`,
	`Even shadows struggle to keep up.`,
	`Fantasy HR called just to whisper "why."`,
	`You dodged emotional damage too.`,
	`Your initiative bonus just took your turn for you.`,
	`You do backflips during conversations. Just because.`,
	`You're legally considered a blur in five realms.`,
	`Even traps hesitate because they know they'll miss.`,
	`You uploaded someone's reflexes and became interpretive parkour.`,
	`Dodged a backstab while tying your shoes.`,
	`The DM said "roll initiative" and you already acted.`,
	`Your idle animation includes flips.`,
	`Locks open themselves when they hear you coming.`,
	`The rogue started taking notes. Reluctantly.`,
	`You sneak so well even gods lose track of you.`,
	`Gravity said "nevermind."`,
];
export const highCon = [
	`Uploaded someone else's stats and became unkillable.`,
	`Your hit points have hit points.`,
	`You sleep in full plate. Voluntarily.`,
	`The cleric is out of a job.`,
	`Poison just tastes like seasoning now.`,
	`Fantasy HR confirmed: you are an OSHA violation in reverse.`,
	`Your death saves rolled a restraining order against death.`,
	`You once swallowed a potion bottle. Whole.`,
	`Uploaded endurance. Became myth.`,
	`You've been hit more times than a bard's mixtape and still walk.`,
	`The DM increased enemy damage. You're still standing.`,
	`Even diseases call ahead to cancel.`,
	`Your organs now have plot armor.`,
	`You don't rest. You choose when damage is allowed.`,
	`Falling damage gets redirected to the ground.`,
	`You tanked so hard the barbarian took notes.`,
	`Your pulse is the campaign tempo.`,
	`You rest by glaring at your wounds until they give up.`,
	`This Constitution stat needs its own insurance.`,
	`You took 20 damage and called it "cute."`,
	`You were uploaded with built-in damage buffering.`,
	`Resting? That's just a courtesy.`,
	`Fireball survivor. Repeatedly.`,
	`Your lungs have lair actions.`,
	`Potions are emotional support, not requirements.`,
	`Fantasy HR issued you a health bar shaped like a mountain.`,
	`The healer retired mid-campaign.`,
	`Even poison has to ask for permission.`,
	`The dragon used breath weapon. You sneezed.`,
	`Your immune system holds grudges.`,
];
export const highWis = [
	`You uploaded someone else's stats and now see into people's backstories.`,
	`Even the gods text you for updates.`,
	`You sense traps in emotional conversations.`,
	`You passed a perception check through a locked door.`,
	`Fantasy HR requested you review their souls for errors.`,
	`Your gut instinct now speaks in riddles.`,
	`The druid nodded at you and turned into a goose. You understood.`,
	`You don't pray. You consult.`,
	`You once avoided an ambush by blinking.`,
	`The forest recognizes you.`,
	`Even the oracle defers to your vibe checks.`,
	`You perceive so hard the DM has to lie.`,
	`Your passive perception rolled a novel.`,
	`Insight checks now come with flashbacks.`,
	`You walk into a room and know who lied to who and why.`,
	`This wisdom has made the rogue nervous.`,
	`You sense plot twists two sessions early.`,
	`Animals speak to you and gossip.`,
	`You uploaded someone's stats and downloaded omnipresence.`,
	`Your survival checks include fire resistance and emotional resilience.`,
	`You uploaded wisdom and immediately spotted the twist villain.`,
	`Perception so high, you see plot hooks forming.`,
	`Insight rolls now come with cutscenes.`,
	`You recognize NPC trauma before they speak.`,
	`Forest creatures nod respectfully when you pass.`,
	`You detected a lie in another campaign.`,
	`Even clerics ask you what the gods meant.`,
	`Every vibe check you make becomes prophecy.`,
	`Wisdom so sharp it counts as a weapon.`,
	`Your dreams have patch notes from reality.`,
];
export const highCha = [
	`You uploaded someone's stats and became the plot hook.`,
	`Even villains hesitate before monologuing around you.`,
	`You roll Persuasion and the mayor retires.`,
	`Uploaded charisma. Got protagonist energy.`,
	`Bards write love songs just by standing near you.`,
	`Your words cause morale shifts.`,
	`Fantasy HR flagged your smile as a magical effect.`,
	`You flirted with a statue and it blushed.`,
	`The tavern applauds when you enter.`,
	`You're the only one allowed to monologue.`,
	`Your compliments grant temporary hit points.`,
	`DM asks for a roll, then sighs when you nat 20 again.`,
	`You could start a cult by accident.`,
	`Even illusions want to look like you.`,
	`You said "hi" and the noble offered their estate.`,
	`You crit a speech and ended a war.`,
	`The bard just called you "boss."`,
	`You made friends with the mimic. It's now your chair.`,
	`You uploaded charm and downloaded power.`,
	`The party lets you talk first. And last. And again.`,
	`You uploaded charm and reality upgraded your lighting.`,
	`Villains pause to ask for a selfie.`,
	`The tavern changed its name to yours mid-session.`,
	`Words come out like music with better acoustics.`,
	`Bards start wars to write about you.`,
	`Even enemies hesitate. You're narratively expensive.`,
	`Charisma that breaks NPC scripting.`,
	`You cast Calm Emotions by walking in.`,
	`Your voice gets bardic inspiration for free.`,
	`The king asked if you're busy next campaign.`,
];

export const lowAvg = [
	`Almost like they tried, but then got distracted.`,
	`The party calls this "the respectable underachiever."`,
	`Not terrible, but definitely needs a pep talk.`,
	`Fantasy HR notes: "Could do worse, but why try?"`,
	`The DM is considering giving you a participation trophy.`,
	`More "trying their best" than "legend in the making."`,
	`At least this upload didn't trigger any warnings.`,
	`The rogue calls it "adequately forgettable."`,
	`You're living proof that average can be... low average.`,
	`The bard's song is mostly about potential.`,
	`This stat is a solid meh.`,
	`Someone pressed the "barely acceptable" button.`,
	`The wizard sighed and said, "You'll get there someday."`,
	`Party morale: cautiously optimistic.`,
	`The cleric said "Bless your effort."`,
	`Not quite epic, but the DM will let it slide.`,
	`The stats committee says, "Try harder next time."`,
	`If this were a saving throw, it'd be a 10.`,
	`You uploaded average, but with a dash of underperformance.`,
	`This character's middle name is "meh."`,
	`You uploaded the stats of a peasant.`,
	`Uploaded stats feel like they took a nap halfway through.`,
	`You might not break the mold, but you won't shatter it either.`,
	`The party looks at you like, "Bless your heart."`,
	`Not bad enough to reroll, but not good enough to brag.`,
	`The wizard said, "I believe in you. Sort of."`,
	`Sometimes just showing up is the adventure.`,
	`Your stats have the enthusiasm of a Monday morning.`,
	`You're the “nice try” of the adventuring world.`,
	`The rogue is confused whether to pity or encourage you.`,
	`Even the NPCs say, "At least they're trying."`,
	`Uploaded stats are like decaf coffee, passable but lacking kick.`,
	`Your best move might be looking busy.`,
	`The DM wonders if this was a quiet protest.`,
	`You bring balance to the party by being, well, balanced.`,
	`Fantasy HR classifies you under "reliable mediocrity."`,
];
export const highAvg = [
	`Somewhere between "almost legendary" and "pretty good."`,
	`The party wonders if you're secretly cheating.`,
	`Stats that say, "I could totally take on a dragon. Maybe."`,
	`Fantasy HR gave you a gold star for effort.`,
	`The DM is suspicious but impressed.`,
	`You're basically the unofficial team MVP.`,
	`The bard's songs include your name in a good light.`,
	`Not quite the hero, but definitely the main supporting act.`,
	`Wizard's note: "Please stop being so consistently capable."`,
	`You uploaded some serious competence.`,
	`This is the sweet spot between chaos and order.`,
	`Party consensus: "We'll take this every day."`,
	`Even the NPCs ask you for advice.`,
	`Your stats come with a side of "respect."`,
	`You're the reliable plot mover.`,
	`The cleric smiles when you walk in the room.`,
	`The DM grits teeth but smiles too.`,
	`Stats that scream "I've got this."`,
	`The rogue grudgingly admits you're useful.`,
	`This character could almost go pro.`,
	`Fantasy HR says, "Good job, but don't get cocky."`,
	`Your stats almost convinced the DM to raise the stakes.`,
	`Party members quietly wonder if you're cheating the system.`,
	`The bard considers writing you a theme song.`,
	`Fantasy HR almost gave you a promotion.`,
	`The wizard checks twice to make sure you're not hacking.`,
	`You make the rest of the party look good by comparison.`,
	`Every roll you make gives the DM a mini heart attack.`,
	`Uploaded stats scream, "I'm ready for the spotlight."`,
	`Even the villains are a bit intimidated.`,
	`You walk in and the stakes get higher.`,
	`The cleric prays a little louder when you're around.`,
	`The rogue tries to mimic your style and fails.`,
	`DM secretly thinks you're the real main character.`,
	`Your competence raises party morale by 20%.`,
	`These stats say, “Legend in progress.”`,
];
export const midAvg = [
	`Clearly, the upload was done by someone with mild standards.`,
	`The party says you're "surprisingly competent" sometimes.`,
	`Stats so balanced they make the DM yawn.`,
	`This is the realm of "just enough."`,
	`Fantasy HR labeled this "standard issue adventurer."`,
	`You're the NPC everyone remembers vaguely.`,
	`The bard sings songs about your average quests.`,
	`Not bad enough to worry, not good enough to brag.`,
	`The wizard calls this "adequate with room for snacks."`,
	`Sometimes you roll well. Other times, it's an adventure.`,
	`Your stats are that one meme: "This is fine."`,
	`Uploaded someone else's stats and hit "normal."`,
	`Party whisper: "At least they don't slow us down."`,
	`The cleric nods with mild approval.`,
	`The DM sets the difficulty to “moderate.”`,
	`Not a hero, not a villain, just... you.`,
	`Your stats are the bread and butter of the adventuring world.`,
	`This character's tagline is "steady if unremarkable."`,
	`The rogue respects your ability to stay out of trouble.`,
	`Balanced enough to not break the game, unfortunately.`,
	`This character knows the meaning of "just enough."`,
	`The party considers you their safe bet.`,
	`Stats like these say "I could surprise you."`,
	`The bard might write a ballad about your quiet heroism.`,
	`The wizard's advice: "Don't get too comfortable."`,
	`You're the calm in the storm of chaos rolls.`,
	`Uploaded stats with a flair for getting the job done.`,
	`The rogue sometimes consults you for basic tactics.`,
	`Your presence is soothing, if not dazzling.`,
	`The DM sets an average challenge to keep you interested.`,
	`You walk the line between “meh” and “momentous.”`,
	`Party morale gets a steady boost from you.`,
	`Fantasy HR says, "Solid performer with potential."`,
	`Not flashy, but you keep the story moving.`,
	`Your stats whisper, “I got your back.”`,
];
