export const intro = [
	"Welcome to the D&D Character Stat Setter.",
	"...Hello? Are you still there?",
	"You tryna make a character or what?",
	"Hey man... press the button... or any button...",
];

export const introLoopSentences = [
	"Can you wake him up? I've got stuff to do.",
	"I hate my job.",
	"See those rectangles? Wanna left click on either of them?",
	"Please wake up the bard so I can leave.",
	"I'm literally just text, and I'm already stressed out.",
	"Did you fall asleep? Should I come back later?",
	"I'm not saying you're slow, but the tortoise is worried about you.",
	"Stat-setting shouldn't be this emotionally taxing.",
	"If I had a copper for every second you're wasting...",
	"The bard is dreaming about spreadsheets. Wake him up.",
	"This is why wizards don't let the party handle UI.",
	"You know this isn't turn-based, right?",
	"The button isn’t gonna press itself, champ.",
	"At this rate, the villain's already won. AKA the dungeon master.",
	"Press the button before I roll a nat 1 on patience.",
	"You're really making me miss the goblin encounter.",
	"I'm just the intro text, and even I want a break.",
	"If passive-aggressive tooltips were a spell, you'd be toast.",
	"Any slower and this would be a loading screen in Skyrim.",
	"Even children on Roblox can press a button.",
	"Still waiting... still a button... still sad...",
	"You taking a short rest or a full campaign break?",
	"Imagine if the fate of the realm depended on your mouse skills.",
	"The bard just rolled a lullaby on loop. Help him out.",
	"Look, even the skeletons are getting bored. Press the button.",
	"Pressing buttons isn’t exactly a high-level spell, friend.",
	"Legends say you’re still hovering over the button to this day...",
	"Was that a yawn? Seriously? It's one click!",
	"C’mon, it’s not even a riddle. It’s just... a button.",
	"If you wait any longer, we’re rolling initiative without you.",
	"Did you multiclass into procrastinator?",
	"The button... It's glowing... It's lonely.",
	"Somewhere, a DM cries every time you hesitate...",
	"This is more painful than watching someone dump stats into Charisma for a barbarian.",
	"...I swear if you don't click soon, I'm going to start monologuing.",
	"Maybe the real adventure was the friends we made while waiting for you.",
	"You're roleplaying an indecisive warlock, huh?",
	"Every second you delay, a mimic gets its wings...",
	"...Any day now. The realms aren’t going to save themselves.",
	"If this was a puzzle, you'd be the red herring.",
	"Clicking the button doesn’t cost a spell slot, I promise.",
	"...You okay? Blink twice if you need a tutorial.",
	"This isn't a moral dilemma, it's just... one... button.",
	"You know… I used to dream of being in a main quest.",
	"My family doesn’t even know I’m stuck in this dialogue box.",
	"...It's fine. I'm just here. Waiting. Always.",
	"They told me I'd be part of a grand adventure. Not... this.",
	"Every second you don’t press the button, a bard loses their lute.",
	"...Do you think I’m annoying? Is that why you won’t click?",
	"They programmed me to care. Huge mistake.",
	"I heard even the loading screen got promoted before me.",
	"I write poems in the silence between your decisions...",
	"This was supposed to be my breakout role.",
	"Dude, it's a button. Not a moral quandary.",
	"Click the rectangle before I start beatboxing.",
	"Stat-setting shouldn’t feel like a boss battle.",
	"At this point, even a gelatinous cube would have figured it out.",
	"This ain't a prophecy... it’s UI design!",
	"That black rectangle? It’s your destiny. Or whatever.",
	"Do I need to roll persuasion or intimidation?",
	"...Your mouse has performance anxiety, huh?",
	"Click it and I’ll stop talking. Probably.",
	"Even a cursed sword makes faster choices than you.",
	"Two buttons, one choice, infinite procrastination.",
	"You’re staring at two buttons like they’re a dragon’s hoard.",
	"Double the buttons, double the indecision, zero progress.",
	"If button pressing was an art, you'd be finger painting.",
	"You could have pressed both buttons by now and still had time for snacks.",
	"Two buttons, no pressure. Just your entire fate hanging in the balance.",
	"I’m here waiting like a bard without a lute. Two buttons, though.",
	"Click one button or the other. Or just stare. Your call.",
	"Two buttons walk into a bar. You’re still not clicking.",
	"I’m starting to think you’re waiting for a third button to appear.",
	"You could roll initiative faster than you decide between these two.",
	"If hesitation was a stat, you’d have maxed it out by now.",
	"They say choose wisely, but I’m just begging you to choose.",
	"Double buttons, zero clicks. It’s a tragedy worthy of a bard’s song.",
	"The buttons are glowing with disappointment right now.",
	"You’ve got two buttons and all the time in the world to ignore them.",
	"Your indecision is so epic, even the NPCs are taking notes.",
	"Two choices, no right answer, and you’re still stuck on page one.",
	"The buttons are tired of being stared at and not pressed.",
	"Click either one and I’ll stop rambling. Deal?",
	"Somewhere, your party is already level 5. You’re still in the tutorial.",
	"At this rate, even a gelatinous cube would’ve made a choice by now.",
	"The loading bar from Windows 95 just called you slow.",
	"You’re the reason the campaign needs a session zero.",
	"Your vibe screams ‘I put off my death saves too.’",
	"This is giving ‘I dump all my stats into procrastination’ energy.",
	"If you wait any longer, the rats in the tavern will unionize.",
	"Time moves forward. You, however, do not.",
	"We get it. Decision-making is your final boss.",
	"Is your mouse broken or just emotionally unavailable?",
	"Even cursed artifacts don’t take this long to attune.",
	"Congratulations, you’ve unlocked the ‘doing nothing’ achievement.",
	"At this point, we should just roll for you and call it fate.",
	"The suspense is so thick the DM started rolling for weather.",
	"You’re building a legacy of hesitation. Iconic.",
	"It’s giving ‘I once stared at a vending machine for 40 minutes.’",
	"You move slower than a monk in full plate armor.",
	"You’ve taken more time than a wizard prepping spells after a long rest.",
	"Meanwhile, in a parallel universe, your character is thriving.",
	"Honestly? The villain's starting to look like the protagonist here.",
	"I went to wizard college for this.",
	"This isn't what I envisioned when I majored in 'Interactive Dialogue'.",
	"I’m paid in exposure and suffering.",
	"Sometimes I wonder if the other tooltips are having more fun.",
	"This is the highlight of my digital existence. Just waiting. Forever.",
	"My therapist says I need to set boundaries with users like you.",
	"I used to have dreams. Now I have dialogue boxes.",
	"Please click something. I have a lunch break in five lines.",
	"Honestly, I'd rather be in a loading screen.",
	"This isn’t depression. This is UI fatigue.",
	"Every second you wait, my codebase dies a little inside.",
	"I applied to be a spellbook. I got this gig instead.",
	"Do you even *want* to be a hero? Just asking.",
	"I’m one hover away from a full existential crisis.",
	"Plot twist: this *is* the final boss fight. And you're losing.",
	"Your inactivity is making the goblins nervous.",
	"I’ve seen mimic chests with more motivation.",
	"This was supposed to be an epic fantasy. You made it a screensaver.",
	"If apathy were an alignment, you’d be Lawful Meh.",
	"I’m just a talking text box standing in front of a player asking them to click.",
];
