export const intro = [
	"Welcome to the D&D Character Stat Setter.",
	"Hello? Are you still there?",
	"You tryna make a character or what?",
	"Hey man... press the blue button.",
];

export const loopSentences = [
	"Can you wake him up? I've got stuff to do.",
	"I hate my job.",
	"See that blue rectangle? Wanna left click on that?",
	"Please wake up the bard so I can leave.",
	"I'm literally just text, and I'm already stressed out.",
	"Did you fall asleep? Should I come back later?",
	"I'm not saying you're slow, but the tortoise is worried about you.",
	"Stat-setting shouldn't be this emotionally taxing.",
	"If I had a copper for every second you're wasting...",
	"The bard is dreaming about spreadsheets. Wake him up.",
	"This is why wizards don't let the party handle UI.",
	"You know this isn't turn-based, right?",
	"The blue button isn’t gonna press itself, champ.",
	"At this rate, the villain's already won. AKA the dungeon master.",
	"Press the button before I roll a nat 1 on patience.",
	"You're really making me miss the goblin encounter.",
	"I'm just the intro text, and even I want a break.",
	"If passive-aggressive tooltips were a spell, you'd be toast.",
	"Any slower and this would be a loading screen in Skyrim.",
	"Even children on Roblox can press a button bro.",
	"Still waiting... still a button... still blue.",
	"You taking a short rest or a full campaign break?",
	"Imagine if the fate of the realm depended on your mouse skills.",
	"The bard just rolled a lullaby on loop. Help him out.",
	"Look, even the skeletons are getting bored. Press the button",
	"Pressing buttons isn’t exactly a high-level spell, friend.",
	"Legends say you’re still hovering over the button to this day...",
	"Was that a yawn? Seriously? It's one click!",
	"C’mon, it’s not even a riddle. It’s just... a button.",
	"If you wait any longer, we’re rolling initiative without you.",
	"Did you multiclass into procrastinator?",
	"It's blue. It's glowing. It's lonely.",
	"Somewhere, a DM cries every time you hesitate...",
	"This is more painful than watching someone dump stats into Charisma for a barbarian.",
	"...I swear if you don't click soon, I'm going to start monologuing.",
	"Maybe the real adventure was the friends we made while waiting for you.",
	"You're roleplaying an indecisive warlock, huh?",
	"Every second you delay, a mimic gets its wings...",
	"...Any day now. The realms aren’t going to save themselves.",
	"If this was a puzzle, you'd be the red herring.",
	"Clicking the button doesn’t cost a spell slot, I promise.",
	"...You okay? Blink twice if you need a tutorial.",
	"This isn't a moral dilemma, it's just... one... button.",
];
