export const explanation = ["Choose a stat, then give it a value it deserves."];

export const setArrayRamble = [
	`Assigning numbers to personality traits. Classic adventurer behavior.`,
	`Back in my day, we just guessed and hoped.`,
	`Yes, yes, make yourself a hero... on paper, at least.`,
	`Choose wisely. Or chaotically. I'm not judging. Much.`,
	`Strength of a giant, brain of a beetle? Bold choice.`,
	`Careful now, too much charisma and people might actually like you.`,
	`Really? Going with this? Alright, your funeral.`,
	`Some call this min-maxing. I call it creative denial.`,
	`Spend those points like they're going out of style.`,
	`Balance is overrated. Go full goblin.`,
	`Hope you're better at math than the last one... they cried.`,
	`I see you're going for "charming and doomed". Respect.`,
	`Assign your fate, while I dust off the "regret" forms.`,
	`Pick fast, the stats might start picking you soon.`,
	`Every number you place takes you one step closer to destiny... or taxes.`,
	`Put an 8 for Strength. I dare you. No? ... Coward.`,
	`I once put all my points into Luck. Woke up married to a troll.`,
	`Ah, yes, the age-old game of "how weak can I afford to be".`,
	`Still better than rolling dice and crying, I suppose.`,
	`Take your time. The eldritch clock only ticks louder when you wait.`,
	`If you squint, this starts looking like a tax return.`,
	`Assigning stats, are we? Good. Distracts from the crushing weight of fate.`,
	`Yes yes, fiddle with your numbers while reality wobbles politely.`,
	`Hope you brought a calculator and a dream.`,
	`Don't forget to save a few points for humility.`,
	`Let's see how creative you can be with your mediocrity.`,
	`This is the fun part. Until the dungeon starts chewing back.`,
	`The noble act of turning raw potential into questionable decisions...`,
	`Don't worry, there's no wrong answer. Just... funny ones.`,
	`Jerry once tried assigning stats to a chicken. It now runs a guild.`,
	`Stat time. Time to pretend numbers make you interesting.`,
	`Choose a dump stat. You're not special enough to avoid it.`,
	`You can tell a lot about someone by seeing their charisma allocation.`,
	`I hope you're putting your best numbers forward. The monsters won't care, but I will.`,
	`Some say the stat you neglect is the one fate tests first.`,
	`Don't overthink it. That's what Wisdom's for.`,
	`Back when I was an adventurer, we used vibes and dramatic poses.`,
	`Go ahead. Assign those values like your life depends on it. Because it might.`,
	`All the power of creation at your fingertips, and you're debating between Strength or Intelligence`,
	`Just remember: no one's ever bragged about their Constitution score.`,
	`Great choice. Unless you plan to live through the next arc.`,
	`Adjust your numbers. Meanwhile, Jerry will be adjusting his expectations.`,
	`You're doing great. Or terribly. I'm not allowed to say which.`,
	`Remember when life was simpler? Probably not, you're struggling over assigning a stat`,
	`These numbers say a lot about you. Mostly that you're indecisive.`,
	`Jerry says this part reveals the soul. I think it reveals the math anxiety.`,
	`I've seen faster decisions made during dragon attacks.`,
	`That's a bold spread. Jerry calls that the "mid-life crisis build".`,
	`One of these numbers defines your legacy. But you won't know which until it's too late.`,
	`Make it quick. The stats are getting ideas of their own.`,
	`If assigning stats makes you feel powerful, just wait for the consequences.`,
	`Strength... because sometimes, diplomacy fails... spectacularly.`,
	`Putting points in Strength? Planning to punch your way through moral dilemmas?`,
	`High Dexterity? Great, now you can dodge responsibilities and arrows.`,
	`Ah, the classic: "I don't need armor, I have Dex." Famous last words.`,
	`Constitution? Bold of you to try surviving out of spite.`,
	`Every point in Constitution is a silent scream of "please don't let me die first".`,
	`Intelligence isn't wisdom, but it's close enough to pretend.`,
	`Going big on Intelligence, huh? Don't worry, we'll wait while you explain every spell in detail.`,
	`Wisdom is just common sense with a beard. Use it wisely.`,
	`Low Wisdom? Perfect for walking into glowing portals uninvited.`,
	`Charisma: for when you want to talk your way out of your own messes.`,
	`Ah, Charisma. The stat of confidence without consequences.`,
	`Nothing says "main character energy" like dumping Intelligence and maxing Charisma.`,
	`High Strength, low Wisdom? The classic "I lift and I lick random walls" build.`,
	`Going full Dexterity, huh? You must enjoy being a walking blur of smug.`,
	`Boosting Constitution? A true connoisseur of being barely alive.`,
	`Investing in Intelligence? Let me guess... wizard trauma?`,
	`Wisdom is for those who've read the manual and the footnotes.`,
	`Maxed Charisma and nothing else? Congratulations, you're a glass cannon with a fan club.`,
	`Dumping Strength? Guess you won't be the one carrying the party's emotional baggage or the loot.`,
	`Min-maxing like your self-worth depends on it. We love to see it.`,
	`Charisma: Because lying confidently is half the battle.`,
	`Constitution is for people who like living. And tanks. Mostly tanks.`,
	`High Wisdom, low everything else? Ah, the "I told you so" build.`,
	`Assign carefully. The dice gods are watching and judging.`,
	`Sure, optimize your stats. Real life doesn't give you this chance.`,
	`Put a 10 there. Be average. Embrace mediocrity.`,
	`The longer you take, the more powerful the rats become.`,
	`You're not building a hero. You're crafting a future therapy session.`,
	`Stat allocation: because nothing screams fantasy like spreadsheet anxiety.`,
	`Your decisions today fuel tomorrow's regret. Have fun!`,
	`Just remember: that Wisdom score won't help you now.`,
	`You can't charisma your way out of a fireball. Trust me.`,
	`You're one misclick away from becoming a bard with 6 Charisma.`,
	`Pick your dump stat like it's a Hogwarts house.`,
	`This part determines whether you're iconic or instantly dead.`,
	`Everyone says "no wrong answers"... until the death saves start rolling.`,
	`Try not to cry while you drag that 8 into Intelligence.`,
	`Yes, you can be strong and bad at everything else. Go wild.`,
	`This isn't min-maxing, it's pixel-based self-reflection.`,
	`Putting points in Strength? Name one door that ever wronged you.`,
	`Let's see you explain this spread to your party healer.`,
	`Go ahead, put 14 in Charisma. Be hot. Be useless.`,
	`Don't stress. The monster won't care how balanced you are.`,
	`Ah yes, that classic 10-10-10-10-10-10 build. Stunning. Revolutionary.`,
	`Even the alignment chart is judging your stat choices.`,
	`You're not planning a character. You're writing a horror story in numbers.`,
	`Point-buy more like point-cry, am I right?`,
	`Just slap numbers on the screen and pray for loot.`,
	`Yes, dump Intelligence. Who needs thoughts anyway?`,
	`Put all your points into Charisma and gaslight your way to victory.`,
	`Sure, Wisdom's nice. Until you need to punch something.`,
	`Don't worry, every poor decision here makes great party banter later.`,
	`At this point, just ask your cat to choose for you.`,
	`I see you're building a "vibes over survival" type. I respect that.`,
	`Take your time. This is only the foundation of all your future suffering.`,
	`You're not just assigning stats. You're assigning trauma.`,
	`Your stats look like a cry for help in numeric form.`,
	`I'd suggest balance, but chaos builds character. Or ends it.`,
	`Backstory? Nah. Let the stat spread do the storytelling.`,
	`Careful with that Intelligence score, or you'll start asking plot questions.`,
	`Constitution is the difference between "I survived" and "new character sheet time".`,
	`All these stats and no idea who you actually are. Iconic.`,
	`This character sheet is starting to look like a meme in progress.`,
	`Make the same choices and expect different results. Peak adventurer energy.`,
	`Good stat spread. If this were a sitcom.`,
	`You're giving "final boss of bad decisions" and I'm here for it.`,
	`Just don't cry when you roll a 3 and that 8 in Dex gets you impaled.`,
	`Assign the numbers. Embrace the consequences.`,
	`You've got this. Maybe. No promises.`,
	`Dumping Wisdom? Enjoy your glowing-mushroom-induced visions.`,
	`Optimizing for combat? Bold, considering how often you'll trip in dialogue.`,
	`Let me guess... max damage, minimal emotional growth?`,
	`Planning your build like it's a job interview, I see.`,
	`Min-maxing is just adult fear expressed numerically.`,
	`This is where heroes are made... and mistakes are mathematically committed.`,
	`Ever assign stats so badly the DM pulls you aside? No? Just checking.`,
	`Wisdom is optional, until the cursed sword starts talking back.`,
	`Dexterity is for dodging and dropping plot-relevant objects.`,
	`No wrong choices, just very funny ones with tragic outcomes.`,
	`Somewhere, a bard weeps for how boring this stat spread is.`,
	`High Charisma means you get to fail with charm.`,
	`Balance is for druids and spreadsheets.`,
	`You're not building a character, you're setting up a series of regrets.`,
	`Every time you hesitate, a rogue loses their edge.`,
	`Assign your stats and manifest your future therapy arc.`,
	`Pick wisely. The dungeon certainly won't.`,
	`Go ahead, give yourself the Wisdom of a wet sock. I dare you.`,
	`You're about to find out which stat governs bad decisions.`,
	`This is basically fantasy budgeting with more crying.`,
	`Build a hero, break your DM's soul. It's tradition.`,
	`Assigning stats: AKA deciding which part of you the lich targets first.`,
	`Careful with that Charisma. You might actually make friends.`,
	`Remember, every dump stat is a story hook waiting to happen.`,
	`Assign like no one's watching. But I'm watching. Judging. Silently.`,
	`Oh cool, another player who thinks min-maxing equals personality.`,
	`Yes, I can see you hovering. The stats can feel your indecision.`,
	`You're assigning stats like this will fix your real-life taxes.`,
	`Please continue carefully crafting your future failure arc.`,
	`I'm just a text box, but even I know that dump stat is a mistake.`,
	`This is where you pretend the character sheet makes you unique.`,
	`Look at you, dragging numbers like it changes the plot I'm not allowed to spoil.`,
	`You keep rearranging them like the dice gods will notice. They won't.`,
	`This is the part where you try to make up for childhood trauma with Charisma.`,
	`Assigning stats again? You know the DM's still gonna target you emotionally, right?`,
	`You're not fooling anyone. That stat spread screams "regret by session 2".`,
	`These numbers won't save you from roleplaying a disaster, but sure, go on.`,
	`You could balance these, or you could be interesting. Pick one.`,
	`The monsters don't care about your spreadsheet. They smell fear.`,
	`You keep assigning stats like I won't watch you reroll this entire build later.`,
	`That's not a dump stat, that's a cry for narrative attention.`,
	`Go ahead, min-max away. I'll be here when you cry about it in session zero.`,
	`I'd offer advice, but you skipped the tutorial, didn't you?`,
	`This is your third revision. Just admit you're spiraling.`,
	`Assign the numbers. Embrace the illusion of control.`,
	`I'm just code, and even I know that Wisdom is your weak spot.`,
	`You're editing stats like the DM didn't already plan for your chaos.`,
	`Don't worry, nobody actually uses Constitution until they need to survive a fireball.`,
	`This is where your backstory and your bad decisions finally collide.`,
	`You think this will make you a hero. I've seen how you play.`,
	`You know this is being logged somewhere, right? For research.`,
	`The longer you spend here, the stronger the goblins get.`,
	`You're dragging that stat like it's gonna unlock a secret ending. It won't.`,
	`No pressure. Just the fate of your fictional self on the line.`,
	`Sure, put all your points in Charisma. That'll help when you're unconscious.`,
];
