export const explanation = ["Choose a stat, then give it a value it deserves."];

export const setArrayRamble = [
	"Assigning numbers to personality traits. Classic adventurer behavior.",
	"Back in my day, we just guessed and hoped.",
	"Yes, yes, make yourself a hero... on paper, at least.",
	"Choose wisely. Or chaotically. I'm not judging. Much.",
	"Strength of a giant, brain of a beetle? Bold choice.",
	"Careful now, too much charisma and people might actually like you.",
	"Really? Going with this? Alright, your funeral.",
	"Some call this min-maxing. I call it creative denial.",
	"Spend those points like they're going out of style.",
	"Balance is overrated. Go full goblin.",
	"Hope you're better at math than the last one... they cried.",
	"I see you're going for 'charming and doomed'. Respect.",
	"Assign your fate, while I dust off the 'regret' forms.",
	"Pick fast, the stats might start picking you soon.",
	"Every number you place takes you one step closer to destiny... or taxes.",
	"Put an 8 there. I dare you. No? Coward.",
	"I once put all my points into Luck. Woke up married to a troll.",
	"Ah, yes, the age-old game of 'how weak can I afford to be'.",
	"Still better than rolling dice and crying, I suppose.",
	"Take your time. The eldritch clock only ticks louder when you wait.",
	"If you squint, this starts looking like a tax return.",
	"Assigning stats, are we? Good. Distracts from the crushing weight of fate.",
	"Yes yes, fiddle with your numbers while reality wobbles politely.",
	"Hope you brought a calculator and a dream.",
	"Don’t forget to save a few points for humility.",
	"Let’s see how creative you can be with your mediocrity.",
	"This is the fun part. Until the dungeon starts chewing back.",
	"The noble act of turning raw potential into questionable decisions...",
	"Don't worry, there's no wrong answer. Just... funny ones.",
	"Jerry once tried assigning stats to a chicken. It now runs a guild.",
	"Stat time. Time to pretend numbers make you interesting.",
	"Choose a dump stat. You’re not special enough to avoid it.",
	"You can tell a lot about someone by seeing their charisma allocation.",
	"I hope you're putting your best numbers forward. The monsters won’t care, but I will.",
	"Some say the stat you neglect is the one fate tests first.",
	"Don't overthink it. That's what Wisdom's for.",
	"Back when I was an adventurer, we used vibes and dramatic poses.",
	"Go ahead. Assign those values like your life depends on it. Because it might.",
	"All the power of creation at your fingertips, and you're debating between 13 and 14.",
	"Just remember: no one’s ever bragged about their Constitution score.",
	"Great choice. Unless you plan to live through the next arc.",
	"Adjust your numbers. Meanwhile, Jerry will be adjusting his expectations.",
	"You're doing great. Or terribly. I’m not allowed to say which.",
	"Remember when life was simpler and you didn’t have to justify putting a 9 in Intelligence?",
	"These numbers say a lot about you. Mostly that you're indecisive.",
	"Jerry says this part reveals the soul. I think it reveals the math anxiety.",
	"I’ve seen faster decisions made during dragon attacks.",
	"That’s a bold spread. Jerry calls that the 'mid-life crisis build.'",
	"One of these numbers defines your legacy. But you won’t know which until it's too late.",
	"Make it quick. The stats are getting ideas of their own.",
	"If assigning stats makes you feel powerful, just wait for the consequences.",
	"Strength... because sometimes, diplomacy fails... spectacularly.",
	"Putting points in Strength? Planning to punch your way through moral dilemmas?",
	"High Dexterity? Great, now you can dodge responsibilities and arrows.",
	"Ah, the classic: 'I don't need armor, I have Dex.' Famous last words.",
	"Constitution? Bold of you to try surviving out of spite.",
	"Every point in Constitution is a silent scream of 'please don't let me die first.'",
	"Intelligence isn't wisdom, but it's close enough to pretend.",
	"Going big on Intelligence, huh? Don't worry, we’ll wait while you explain every spell in detail.",
	"Wisdom is just common sense with a beard. Use it wisely.",
	"Low Wisdom? Perfect for walking into glowing portals uninvited.",
	"Charisma: for when you want to talk your way out of your own messes.",
	"Ah, Charisma. The stat of confidence without consequences.",
	"Nothing says 'main character energy' like dumping Intelligence and maxing Charisma.",
	"High Strength, low Wisdom? The classic 'I lift and I lick random walls' build.",
	"Going full Dexterity, huh? You must enjoy being a walking blur of smug.",
	"Boosting Constitution? A true connoisseur of being barely alive.",
	"Investing in Intelligence? Let me guess... wizard trauma?",
	"Wisdom is for those who’ve read the manual and the footnotes.",
	"Maxed Charisma and nothing else? Congratulations, you're a glass cannon with a fan club.",
	"Dumping Strength? Guess you won’t be the one carrying the party’s emotional baggage or the loot.",
	"Min-maxing like your self-worth depends on it. We love to see it.",
	"Charisma: Because lying confidently is half the battle.",
	"Constitution is for people who like living. And tanks. Mostly tanks.",
	"High Wisdom, low everything else? Ah, the 'I told you so' build.",
];
