export const introShopText = [
	"Ah, yes... the build-your-own-hero kit.",
	"Because why gamble when you can spreadsheet your way to greatness?",
	"Min-maxing your destiny, one stat point at a time.",
	"Nothing says adventure like responsible budgeting.",
	"Welcome to the stat market. Please shop responsibly.",
	"Fate is for peasants... you have math.",
	"Behold, the power of planning... and mild anxiety.",
	"Rolls? No thanks, I brought a calculator.",
	"Because chaos is scary and control is comforting.",
	"You didn’t roll for stats, you negotiated them.",
	"The dice gods frown upon you, but the nerd gods nod in approval.",
	"Custom-built like a luxury cart... with optimized horsepower.",
	"Finally, a system where intelligence is more than a dump stat.",
	"You're not building a character, you're crafting an optimized masterpiece.",
	"Control freak? No, you're just fate-averse.",
	"Every number has a purpose. Every dump stat, a strategy.",
	"Who needs luck when you’ve got spreadsheets and trauma?",
	"You walked into destiny's casino, took one look, and chose accounting.",
	"This build was made with precision... and probably a tier list.",
	"Your stats may lack chaos, but they have vision.",
	"Point-buy: where dreams are bought, and dump stats are sold.",
	"This is less a character sheet, more a carefully curated experience.",
	"Adventuring is unpredictable... but your Wisdom score isn’t.",
	"A tale of glory, tragedy... and strict point allocation.",
	"Optimization is an art. And you, my friend, are painting in decimals.",
	"Slay, stat queen. Dump Strength, live pretty.",
	"You understood the assignment, and assigned every point flawlessly.",
	"Welcome to the forge where stats are crafted, not cast.",
	"Precision. Balance. Calculation. And maybe a little madness.",
	"Point allocation complete. Efficiency: optimal.",
	"Crafted with care... and a slight obsession with Charisma modifiers.",
	"Your build reads like blueprints. And that’s a compliment.",
	"Beauty lies in numbers and yours are symmetrical.",
	"Oh... you're one of those players...",
	"Somewhere, a dice is weeping.",
	"I had a whole table of chaos ready... but sure, this works too.",
	"The gods of chance turn their backs in boredom.",
	"You dodged fate like it owed you money.",
	"Ah, yes, the accountant’s approach to heroism.",
	"You didn’t roll stats, you filed a tax return.",
	"Point-buy? Bold choice for someone who fears chaos.",
	"Your character sheet has more math than my thesis.",
	"Congratulations, you min-maxed your personality.",
	"Ah, yes, power without the panic.",
	"You walked into a tavern and immediately negotiated.",
	"Spreadsheets AND swordplay? Iconic.",
	"Perfectly planned, emotionally unavailable.",
	"This isn't a character... it's a performance review.",
	"You didn’t roll a hero, you project-managed one.",
	"Your stats are cleaner than a cleric’s conscience.",
	"Point-buy: because chaos is for amateurs.",
	"You're not adventuring, you're executing a strategic initiative.",
];

export const explanationPointLimitText = [
	"Now how many points are you willing to spend today?",
];

export const shopKeeperWakeUp = [
	[
		"...A traveller? Been seeing a bunch of you guys around...",
		"Let me set up my shop, give me a bit...",
	],
	[
		"...Who dares wake me up at this time? Oh...",
		"Let me finish up and I'll be right with you...",
	],
	[
		"...Another one? Did the sign say 'eternal torment' or 'limited-time deals'?",
		"Alright, dusting off the shelves... again.",
	],
	[
		"...You smell like coin. I like that.",
		"Let me just unseal the bargain bin.",
	],
	[
		"...Back already? Didn't you leave ten minutes ago?",
		"Fine, let me reanimate the register.",
	],
	["...You're either brave or very lost.", "Either way, business is business."],
	[
		"...Oh. A customer. I suppose the stars align once more.",
		"Let me align my wares in turn.",
	],
	[
		"...I was just communing with the void. You interrupted.",
		"Now I must balance the ledgers again.",
	],
	[
		"...You broke the silence. You pay the price.",
		"Let me check what that price is today.",
	],
	[
		"...I was dreaming of a world without haggling.",
		"Guess I'll restock the dreamcatchers.",
	],
	[
		"...Welcome, I guess. Your aura screams indecision.",
		"Perfect for our clearance rack.",
	],
	[
		"...Do you even know what time it is in spectral hours?",
		"No matter. The shop obeys no clock.",
	],
	[
		"...If you're here for cursed items, take a number.",
		"Actually, wait... you're the only one here.",
	],
	[
		"...Let me guess, looking for 'just one thing'?",
		"That thing is probably cursed. I’ll go fetch it.",
	],
	[
		"...Customer? No, apparition. Wait... no, you're real.",
		"Okay, firing up the pricing incantation.",
	],
	[
		"...You're early. The whispers hadn't even finished warning me.",
		"Let me sweep the bones off the counter real quick.",
	],
	[
		"...Another soul wandered in, huh?",
		"Let me snuff the candles and light the lanterns... or was it the other way around?",
	],
	[
		"...You stepped on the welcome rune. Bold choice.",
		"I’ll start unlocking the display case of... misunderstood artifacts.",
	],
	[
		"...I smelled fresh intentions. Had to investigate.",
		"Give me a moment to unshrink the furniture.",
	],
	[
		"...You’re glowing slightly. Did you bring magic in here?",
		"Let me check the wards, last time we had a leak, the floor almost bit someone.",
	],
	[
		"...The winds told me you'd arrive.",
		"They also told me to upsell. Interesting.",
	],
	[
		"...You again? The door creaked your name.",
		"Let me make sure the mimic’s pretending to be a chest again.",
	],
	[
		"...You didn’t say the chant right, but I’ll allow it.",
		"The shop doesn’t open for just anyone. Feel flattered.",
	],
	[
		"...A lively one. Most customers come in dreaming, leave screaming.",
		"Let me fetch the less bitey trinkets.",
	],
	[
		"...Oh good, something with eyes has entered.",
		"Let me silence the jars. They're excited.",
	],
	[
		"...You brought sunlight in here. Rude.",
		"Let me drape the gloom back over the shelves.",
	],
	[
		"...That's not how you knock, but I suppose it'll do.",
		"I'll stir the cauldron of clearance deals.",
	],
	[
		"...The bell tolled, and so I rise.",
		"Let me sweep up the dreams spilled from last night.",
	],
	[
		"...You're a peculiar flavor of brave, aren't you?",
		"I’ll sort the talking skulls... they’ve been judging everything lately.",
	],
];

export const alertShopKeeper = [
	"Alright, let me go grab the intern. Don't be alarmed.",
	"One moment... waking up the shopkeeper from his 300-year nap.",
	"Alright, let me summon the keeper of slightly overpriced wares.",
	"Calling the shopkeeper... please hold your breath and your judgment.",
	"Brb, poking Jerry with a stick until he responds.",
	"Hang tight... Jerry's just rearranging the cursed items again.",
	"Fetching the shopkeeper... or at least his hat.",
	"Alright, rustling the curtains of mystery and capitalism...",
	"Shopkeeper’s on their third coffee. You're in luck.",
	"Calling the shopkeeper. If he asks, you didn’t touch anything.",
	"Let me go get the sentient pricing algorithm... I mean, shopkeeper.",
	"Give me a sec... translating your presence into goldlust.",
	"Summoning the one who knows the true price of everything.",
	"Be cool... the shopkeeper bites when startled.",
	"Just a moment... disarming the trap behind the counter first.",
	"Alerting the shopkeeper. Yes, he charges extra for eye contact.",
	"One moment... Jerry's finishing a conversation with something in the cellar.",
	"Don't worry if you hear whispering. That's just the welcoming protocol.",
	"I’ll just peel back the curtain... ignore the eyes.",
	"The shopkeeper is... watching. Always watching. I’ll let him know you're ready.",
	"Summoning this shopkeeper requires exact phrasing. And a drop of ink. Or blood.",
	"Jerry’s just rearranging the shelves. They rearrange back if he stops.",
	"Careful~ Jerry bites if startled. Let me go first.",
	"One sec... the shopkeeper's calibrating the price hexes.",
	"Jerry’ll come out once the shop stops breathing.",
	"Let me just turn this mirror three times and knock twice...",
	"Jerry insists on entering dramatically. Don’t mention the fog.",
	"Bringing Jerry out of his salt circle now... slowly...",
	"Hang tight... the lock on his cabinet of selves is tricky.",
	"Ol' shopkeeper's just finishing his tea… it screams, but he says that’s normal.",
	"I’ll knock three times. If Jerry answers twice, we wait.",
	"Hold on… the shopkeeper is molting.",
	"Don't touch anything glowing. Especially if it purrs.",
	"The shopkeeper will be right out… once the hourglass stops flowing up.",
	"The wards are dimming. That means Jerry is almost lucid.",
	"I heard the trapdoor click... Jerry is on the way.",
	"The shopkeeper is arguing with the broom again. The broom wins most days.",
	"Jerry just needs to finish whispering to the coins.",
	"The shopkeeper is behind the curtain. Or under the floorboards. Or both.",
	"He’s behind the curtain. Or under the floorboards. Or both.",
	"I wouldn’t call it ‘alive,’ but yes, the shopkeeper is present.",
	"He’s polishing the cursed spoons. Give him a moment.",
];
