export const introShopText = [
	"Ah, yes... the build-your-own-hero kit.",
	"Because why gamble when you can spreadsheet your way to greatness?",
	"Min-maxing your destiny, one stat point at a time.",
	"Nothing says adventure like responsible budgeting.",
	"Welcome to the stat market. Please shop responsibly.",
	"Fate is for peasants... you have math.",
	"Behold, the power of planning... and mild anxiety.",
	"Rolls? No thanks, I brought a calculator.",
	"Because chaos is scary and control is comforting.",
	"You didn’t roll for stats, you negotiated them.",
	"The dice gods frown upon you, but the nerd gods nod in approval.",
	"Custom-built like a luxury cart... with optimized horsepower.",
	"Finally, a system where intelligence is more than a dump stat.",
	"You're not building a character, you're crafting an optimized masterpiece.",
	"Control freak? No, you're just fate-averse.",
	"Every number has a purpose. Every dump stat, a strategy.",
	"Who needs luck when you’ve got spreadsheets and trauma?",
	"You walked into destiny's casino, took one look, and chose accounting.",
	"This build was made with precision... and probably a tier list.",
	"Your stats may lack chaos, but they have vision.",
	"Point-buy: where dreams are bought, and dump stats are sold.",
	"This is less a character sheet, more a carefully curated experience.",
	"Adventuring is unpredictable... but your Wisdom score isn’t.",
	"A tale of glory, tragedy... and strict point allocation.",
	"Optimization is an art. And you, my friend, are painting in decimals.",
	"Slay, stat queen. Dump Strength, live pretty.",
	"You understood the assignment, and assigned every point flawlessly.",
	"Welcome to the forge where stats are crafted, not cast.",
	"Precision. Balance. Calculation. And maybe a little madness.",
	"Point allocation complete. Efficiency: optimal.",
	"Crafted with care... and a slight obsession with Charisma modifiers.",
	"Your build reads like blueprints. And that’s a compliment.",
	"Beauty lies in numbers and yours are symmetrical.",
	"Oh... you're one of those players...",
	"Somewhere, a dice is weeping.",
	"I had a whole table of chaos ready... but sure, this works too.",
	"The gods of chance turn their backs in boredom.",
	"You dodged fate like it owed you money.",
	"Ah, yes, the accountant’s approach to heroism.",
	"You didn’t roll stats, you filed a tax return.",
	"Point-buy? Bold choice for someone who fears chaos.",
	"Your character sheet has more math than my thesis.",
	"Congratulations, you min-maxed your personality.",
	"Ah, yes, power without the panic.",
	"You walked into a tavern and immediately negotiated.",
	"Spreadsheets AND swordplay? Iconic.",
	"Perfectly planned, emotionally unavailable.",
	"This isn't a character... it's a performance review.",
	"You didn’t roll a hero, you project-managed one.",
	"Your stats are cleaner than a cleric’s conscience.",
	"Point-buy: because chaos is for amateurs.",
	"You're not adventuring, you're executing a strategic initiative.",
];

export const explanationPointLimitText = [
	"Now how many points are you willing to spend today?",
];

export const shopKeeperWakeUp = [
	[
		"...A traveller? Been seeing a bunch of you guys around...",
		"Let me set up my shop, give me a bit...",
	],
	[
		"...Who dares wake me up at this time? Oh...",
		"Let me finish up and I'll be right with you...",
	],
	[
		"...Another one? Did the sign say 'eternal torment' or 'limited-time deals'?",
		"Alright, dusting off the shelves... again.",
	],
	[
		"...You smell like coin. I like that.",
		"Let me just unseal the bargain bin.",
	],
	[
		"...Back already? Didn't you leave ten minutes ago?",
		"Fine, let me reanimate the register.",
	],
	["...You're either brave or very lost.", "Either way, business is business."],
	[
		"...Oh. A customer. I suppose the stars align once more.",
		"Let me align my wares in turn.",
	],
	[
		"...I was just communing with the void. You interrupted.",
		"Now I must balance the ledgers again.",
	],
	[
		"...You broke the silence. You pay the price.",
		"Let me check what that price is today.",
	],
	[
		"...I was dreaming of a world without haggling.",
		"Guess I'll restock the dreamcatchers.",
	],
	[
		"...Welcome, I guess. Your aura screams indecision.",
		"Perfect for our clearance rack.",
	],
	[
		"...Do you even know what time it is in spectral hours?",
		"No matter. The shop obeys no clock.",
	],
	[
		"...If you're here for cursed items, take a number.",
		"Actually, wait... you're the only one here.",
	],
	[
		"...Let me guess, looking for 'just one thing'?",
		"That thing is probably cursed. I’ll go fetch it.",
	],
	[
		"...Customer? No, apparition. Wait... no, you're real.",
		"Okay, firing up the pricing incantation.",
	],
	[
		"...You're early. The whispers hadn't even finished warning me.",
		"Let me sweep the bones off the counter real quick.",
	],
	[
		"...Another soul wandered in, huh?",
		"Let me snuff the candles and light the lanterns... or was it the other way around?",
	],
	[
		"...You stepped on the welcome rune. Bold choice.",
		"I’ll start unlocking the display case of... misunderstood artifacts.",
	],
	[
		"...I smelled fresh intentions. Had to investigate.",
		"Give me a moment to unshrink the furniture.",
	],
	[
		"...You’re glowing slightly. Did you bring magic in here?",
		"Let me check the wards, last time we had a leak, the floor almost bit someone.",
	],
	[
		"...The winds told me you'd arrive.",
		"They also told me to upsell. Interesting.",
	],
	[
		"...You again? The door creaked your name.",
		"Let me make sure the mimic’s pretending to be a chest again.",
	],
	[
		"...You didn’t say the chant right, but I’ll allow it.",
		"The shop doesn’t open for just anyone. Feel flattered.",
	],
	[
		"...A lively one. Most customers come in dreaming, leave screaming.",
		"Let me fetch the less bitey trinkets.",
	],
	[
		"...Oh good, something with eyes has entered.",
		"Let me silence the jars. They're excited.",
	],
	[
		"...You brought sunlight in here. Rude.",
		"Let me drape the gloom back over the shelves.",
	],
	[
		"...That's not how you knock, but I suppose it'll do.",
		"I'll stir the cauldron of clearance deals.",
	],
	[
		"...The bell tolled, and so I rise.",
		"Let me sweep up the dreams spilled from last night.",
	],
	[
		"...You're a peculiar flavor of brave, aren't you?",
		"I’ll sort the talking skulls... they’ve been judging everything lately.",
	],
	[
		"...Huh. You again. Or... not yet?",
		"Let me realign the clocks. Time’s been folding funny this week.",
	],
	[
		"...That ripple in the curtain wasn't wind. Was it you?",
		"I'll adjust the shelves... they’ve drifted into the wrong dimension again.",
	],
	[
		"...I just saw you leave through the back. Curious.",
		"Let me check which timeline the discount bin is in.",
	],
	[
		"...The portal burped. Must mean we’ve got company.",
		"Let me recage the gremlins before they smell your wallet.",
	],
	[
		"...You’ve stepped between ticks of the hourglass. Impressive.",
		"Give me a moment to stabilize the shop’s reality anchor.",
	],
	[
		"...Oh, the cat noticed you first. That's... rare.",
		"Let me put her crown back on. She's very particular about that.",
	],
	[
		"...You're not made of smoke and teeth. That's refreshing.",
		"I'll get the translator stone so we can barter without nightmares.",
	],
	[
		"...You tracked in static from the other side.",
		"I’ll need to recalibrate the prices. They’re whispering nonsense again.",
	],
	[
		"...My familiar perked up. Either you’re a customer or cursed.",
		"Let me light the polite candle... it keeps the rude items quiet.",
	],
	[
		"...You’re late. Or early. Or both.",
		"I’ll stabilize the doorway before it loops again.",
	],
	[
		"...Don’t move. Something came through with you.",
		"I'll sweep it back into the dimension bin. Happens all the time.",
	],
	[
		"...Welcome. The shop likes you. That's rare.",
		"I'll loosen the chains a bit... things get grabby when excited.",
	],
	[
		"...Oh great. Another customer. Just what I needed.",
		"Let me shuffle some overpriced goods around and pretend I care.",
	],
	[
		"...Ugh. I was having a perfectly good nap-slash-trance.",
		"Fine, let me turn the lights on. Metaphorically.",
	],
	[
		"...You again? I swear I quit centuries ago.",
		"Let me see if the counter still accepts hope as payment.",
	],
	[
		"...Fantastic. Another wide-eyed adventurer with zero patience.",
		"Give me a second to look busy and emotionally detached.",
	],
	[
		"...I should've taken that apprenticeship in necro-accounting.",
		"Alright, let’s get this over with before my soul leaks out again.",
	],
	[
		"...I used to have dreams, you know.",
		"Let me dust off the ‘bargains’ and fake a smile.",
	],
	[
		"...Is it still called ‘customer service’ if I actively dislike it?",
		"Give me a sec to light the candle of feigned enthusiasm.",
	],
	[
		"...Oh, a hero. How original.",
		"I’ll unlock the cabinet of disappointment just for you.",
	],
	[
		"...Don’t mind me, just questioning all my life choices.",
		"Let me activate the till. It sighs louder than I do.",
	],
	[
		"...You break it, you buy it. No refunds, no joy.",
		"Let me retrieve the ledger of shattered expectations.",
	],
	[
		"...Ugh, customer detected. Fine, initiating consciousness.",
		"Let me unlock the display case of suspiciously identical items.",
	],
	[
		"...Oh good, someone to interrupt my existential crisis.",
		"Let me pretend I enjoy this job for a moment.",
	],
	[
		"...Back so soon? I was mid-nap, mid-dream, and mid-regret.",
		"Give me a sec to recalibrate my fake enthusiasm.",
	],
	[
		"...I see we’re doing this now. Great.",
		"Let me straighten my robes and my attitude.",
	],
	[
		"...Another customer. Joy unbounded.",
		"I'll go dust off the inventory and my will to live.",
	],
	[
		"...They told me this would be a quiet post.",
		"Let me re-enable the definitely-not-cursed till.",
	],
	[
		"...Yes yes, awaken the great Jerry. Again.",
		"I'll find my ledger. It bites, so give me a second.",
	],
	[
		"...You know there's a self-service kiosk, right?",
		"Fine, I'll be helpful. Or at least visible.",
	],
	[
		"...Oh, you're not a hallucination. Yet.",
		"Let me disable the ward that turns visitors into frogs.",
	],
	[
		"...And I was just getting good at avoiding work.",
		"Let me summon the catalog of poorly organized goods.",
	],
];

export const alertShopKeeper = [
	"Alright, let me go grab the intern. Don't be alarmed.",
	"One moment... waking up the shopkeeper from his 300-year nap.",
	"Alright, let me summon the keeper of slightly overpriced wares.",
	"Calling the shopkeeper... please hold your breath and your judgment.",
	"Brb, poking Jerry with a stick until he responds.",
	"Hang tight... Jerry's just rearranging the cursed items again.",
	"Fetching the shopkeeper... or at least his hat.",
	"Alright, rustling the curtains of mystery and capitalism...",
	"Shopkeeper’s on their third coffee. You're in luck.",
	"Calling the shopkeeper. If he asks, you didn’t touch anything.",
	"Let me go get the sentient pricing algorithm... I mean, shopkeeper.",
	"Give me a sec... translating your presence into goldlust.",
	"Summoning the one who knows the true price of everything.",
	"Be cool... the shopkeeper bites when startled.",
	"Just a moment... disarming the trap behind the counter first.",
	"Alerting the shopkeeper. Yes, he charges extra for eye contact.",
	"One moment... Jerry's finishing a conversation with something in the cellar.",
	"Don't worry if you hear whispering. That's just the welcoming protocol.",
	"I’ll just peel back the curtain... ignore the eyes.",
	"The shopkeeper is... watching. Always watching. I’ll let him know you're ready.",
	"Summoning this shopkeeper requires exact phrasing. And a drop of ink. Or blood.",
	"Jerry’s just rearranging the shelves. They rearrange back if he stops.",
	"Careful~ Jerry bites if startled. Let me go first.",
	"One sec... the shopkeeper's calibrating the price hexes.",
	"Jerry’ll come out once the shop stops breathing.",
	"Let me just turn this mirror three times and knock twice...",
	"Jerry insists on entering dramatically. Don’t mention the fog.",
	"Bringing Jerry out of his salt circle now... slowly...",
	"Hang tight... the lock on his cabinet of selves is tricky.",
	"Ol' shopkeeper's just finishing his tea… it screams, but he says that’s normal.",
	"I’ll knock three times. If Jerry answers twice, we wait.",
	"Hold on… the shopkeeper is molting.",
	"Don't touch anything glowing. Especially if it purrs.",
	"The shopkeeper will be right out… once the hourglass stops flowing up.",
	"The wards are dimming. That means Jerry is almost lucid.",
	"I heard the trapdoor click... Jerry is on the way.",
	"The shopkeeper is arguing with the broom again. The broom wins most days.",
	"Jerry just needs to finish whispering to the coins.",
	"The shopkeeper is behind the curtain. Or under the floorboards. Or both.",
	"He’s behind the curtain. Or under the floorboards. Or both.",
	"I wouldn’t call it ‘alive,’ but yes, the shopkeeper is present.",
	"He’s polishing the cursed spoons. Give him a moment.",
	"Let me just rattle the bell Jerry responds to. Or growls at.",
	"Hang tight... the shopkeeper’s just finishing a staring contest with a mirror.",
	"I’ll go unseal the door behind which Jerry naps. Loudly.",
	"One second... waking the shopkeeper by humming the cursed tune.",
	"Just a moment... Jerry’s meditating inside a barrel again.",
	"Alerting the shopkeeper... Jerry insists on a dramatic entrance every time.",
	"Hold on, I need to reset the summoning stones. Jerry’s picky about the order.",
	"Opening the drawer labeled ‘Shopkeeper: DO NOT OPEN.’ Here goes.",
	"Jerry’s currently reorganizing the dust by emotional weight. Be right with you.",
	"Don't mind the growling. That just means the shopkeeper’s almost coherent.",
	"Lighting the candle of awareness... if it flickers purple, Jerry’s listening.",
	"Let me adjust the curtains of misfortune. That’s Jerry’s signal.",
	"One moment... the shopkeeper’s arguing with the price tags again.",
	"Just a sec... Jerry’s trapped in a philosophical debate with a coat rack.",
	"Summoning Jerry... please ignore the floating sigils and slight burning smell.",
	"I’ll just jiggle the lantern three times. That usually wakes the shopkeeper.",
	"Calling the shopkeeper... if you feel a chill, that’s confirmation.",
	"Jerry responds well to compliments. Or loud clapping. We’ll try both.",
	"Warning: summoning Jerry may cause brief existential dread. It passes.",
	"Hold still. The shopkeeper gets spooked if you make eye contact too soon.",
	"Let me just rattle the bell Jerry responds to. Or growls at.",
	"Hang tight... the shopkeeper’s just finishing a staring contest with a mirror.",
	"I’ll go unseal the door behind which Jerry naps. Loudly.",
	"One second... waking the shopkeeper by humming the cursed tune.",
	"Just a moment. Jerry’s meditating inside a barrel again.",
	"Alerting the shopkeeper... Jerry insists on a dramatic entrance every time.",
	"Hold on, I need to reset the summoning stones. Jerry’s picky about the order.",
	"Opening the drawer labeled ‘Shopkeeper: DO NOT OPEN.’ Here goes.",
	"Jerry’s currently reorganizing the dust by emotional weight. Be right with you.",
	"Don't mind the growling. That just means the shopkeeper’s almost coherent.",
	"Lighting the candle of awareness... if it flickers purple, Jerry’s listening.",
	"Let me adjust the curtains of misfortune. That’s Jerry’s signal.",
	"One moment... the shopkeeper’s arguing with the price tags again.",
	"Just a sec... Jerry’s trapped in a philosophical debate with a coat rack.",
	"Summoning Jerry... please ignore the floating sigils and slight burning smell.",
	"I’ll just jiggle the lantern three times. That usually wakes the shopkeeper.",
	"Calling the shopkeeper if you feel a chill, that’s confirmation.",
	"Jerry responds well to compliments. Or loud clapping. We’ll try both.",
	"Warning: summoning Jerry may cause brief existential dread. It passes.",
	"Hold still... the shopkeeper gets spooked if you make eye contact too soon.",
	"Notifying the shopkeeper... please allow 3–5 business incantations.",
	"Filing a formal request for Jerry to acknowledge your existence.",
	"Paging the shopkeeper. Your patience is appreciated and legally required.",
	"Submitting a ‘customer detected’ report to Jerry’s desk. It’s... sticky.",
	"One sec, updating Jerry’s ‘motivated to move’ status... still pending.",
	"I’ve escalated your presence to Tier 1 awareness. Jerry will be with you shortly.",
	"Initiating ancient protocol 12-B: wake shopkeeper, avoid eye contact.",
	"Starting the 12-step ‘summon Jerry without fire’ process.",
	"Requesting shopkeeper presence... estimated arrival time: eventually.",
	"Firing off a quick flare. Jerry hates those. He’ll show up.",
	"Sending a strongly worded whisper into the void. Jerry's preferred memo format.",
	"Beginning the ceremonial ‘knock, sigh, knock again’ sequence.",
	"Logging a complaint with the universe. It’ll route to Jerry.",
	"Just texted the shopkeeper: ‘u up?’ It usually works.",
	"Hang tight, I’m bribing the door to let Jerry through.",
	"Starting Jerry’s wake-up playlist. First song: 'Why Am I Awake'.",
	"Just clicked ‘Remind Jerry in 5 minutes’ for the 6th time.",
	"Lighting the incense of mild urgency. Jerry hates that one.",
	"I'll go press the enchanted doorbell. It screams, but Jerry hears it.",
	"Turning the crank labeled ‘Customer Incoming’. Jerry installed it himself. Ironically.",
];

export const shopKeeperRamble = [
	"Back in my day, we didn’t buy stats... we earned them by surviving the swamp trials.",
	"Reminds me of a bard I once sold a spoon to. Didn’t end well for the spoon.",
	"I knew a rogue once. Had ten fingers when we met, five by the time he left.",
	"Every time someone invests in Intelligence, the candles flicker. Not sure why.",
	"Ah, the sweet smell of min-maxing. Like wet socks and ambition.",
	"Take your time. The cursed hourglass doesn’t technically exist here.",
	"You know, in some cultures, Wisdom is inherited. In others, purchased. Guess which one this is.",
	"Once had a wizard max out Constitution. Now runs a bakery. Never looked back.",
	"I used to sell dreams. Now I sell stat points. Same thing, just sadder.",
	"There's a tax for every point you don't spend wisely. Not gold. Just... regret.",
	"You can put points into Strength, but it won't fix your posture.",
	"I’ve seen someone put all their points into Luck once. Haven’t seen them since.",
	"That look on your face? That’s buyer’s remorse forming.",
	"This part’s always the same. Eyes wide, coin purse open, zero foresight.",
	"That’s a solid build. If you’re planning to die stylishly.",
	"If I had a copper for every foolish stat allocation I’ve witnessed... oh wait, I do.",
	"Balance is for tightrope walkers and indecisive paladins.",
	"Spend it all now, regret it later. It’s the adventurer’s way.",
	"Heard of the classic Strength and Charisma combo. Hit hard, flirt harder.",
	"You can optimize all you want. The dungeon doesn’t care.",
	"Back when I had stats, I maxed out Apathy. Served me well.",
	"Careful now. That’s how the last customer accidentally became a frog.",
	"Planning a build, are we? Delightful. The monsters will love it.",
	"Have you considered dumping everything into Vibes? No? Coward.",
	"Once had a customer pour every point into Intelligence. Now teaches slugs to dance.",
	"They say every point spent echoes through the void. I say it jingles in my coin jar.",
	"Oh good, another custom build. Haven’t seen that fail spectacularly... this week.",
	"All these points and still no one invests in common sense.",
	"You could put points into Strength. Or, hear me out... bribe the monster.",
	"Some say the perfect build exists. They’re buried under the store.",
	"Making a decision? That’s adorable.",
	"One time someone asked for a refund. Now they live in the mirror.",
	"I've met paladins with better point spreads. And paladins are allergic to creativity.",
	"Yes yes, take your time. The rats haven’t organized yet.",
	"I like the way you're thinking. Mostly because it’s bad for your survival.",
	"Keep going. The stat screen likes watching people struggle.",
	"Go on, overthink it. The spirits are very entertained.",
	"Reminds me of a monk who dumped Wisdom. He walks into walls now. Philosophically.",
	"I used to have stats. Then I opened a shop.",
	"I’ve seen better builds on a soup spoon.",
	"If you're still here in 10 minutes, the furniture starts whispering ideas.",
	"You can respec later, sure. If you survive the paperwork trial.",
	"How exciting. You’re inventing a new way to fail forward.",
	"That’s it, make it personal. The stats love attention.",
	"This is the part where the fate-weavers usually start cackling.",
	"You’ve got that look... the one that says, I read one forum post.",
	"Careful. If you spend wrong, the stat screen bites.",
	"Mm. This part always reminds me of that adventurer who couldn't decide... they’re still deciding, probably.",
	"Back in my day, we just picked a number and prayed. None of this fancy thinking business.",
	"Ah, takes me back. Long nights by candlelight, rerolling dice and regretting everything.",
	"I remember when points meant something. Now? Just numbers and delusions.",
	"Last time someone took this long, the dungeon evolved sentience and left.",
	"You ever just stare at numbers until they start whispering your name? No? Huh.",
	"This part used to be sacred. Now it’s all sliders and shiny buttons. Progress, I guess.",
	"Had a customer once who closed their eyes and clicked randomly. Legend says they lived. Briefly.",
	"Y’know, I used to spend points too. Then I spent one on retail management. Curse lasted forever.",
	"Time was, you'd carve your stats into stone and bleed on them for good luck. Kids these days...",
	"I can still smell the fire from the last stat allocation gone wrong. Mmm. Smoky ambition.",
	"Ah yes... this silence. Reminds me of that time the points fought back.",
	"I used to dream of points. Now I just dream of dust and return policies.",
	"Careful now. The last one who hesitated this long developed a second conscience.",
	"Reminds me of that one adventurer who sat right there... just like you... never left.",
	"There was a time when allocating points was an art. Now it’s more of a public hazard.",
	"Strange, how something so simple can feel like rewriting fate. Or maybe I’m just dramatic.",
	"Once knew a bard who never finished this step. Haunts the dropdown menus now.",
	"Had a wizard spend all their points, then immediately try to unlive their decision. Not pretty.",
	"These quiet moments always get me thinking. And thinking leads to regret. Careful with that.",
	"Ah, the delicate art of min-maxing. You remind me of a wizard who exploded.",
	"Take your time, really. It's not like I'm bound to this counter for eternity or anything.",
	"Back in my day, we didn’t have points. We had grit, and tetanus.",
	"Careful how you spread those points. I once saw someone dump it all into charisma and spontaneously combust.",
	"Balance is key. Or chaos. Either works, I suppose.",
	"You know, in the end, we’re all just poorly-optimized stat blocks.",
	"I once sold a sword that whispered nightmares. Got excellent reviews.",
	"Want my advice? Don’t ask a guy whose best friend is a talking candle.",
	"You're doing great. Really. Just don’t forget to leave some points for common sense.",
	"I had a customer once who chose all 8s. Said they wanted the true peasant experience.",
	"Ah, the thrill of numbers. Riveting stuff. No, seriously, I live for this.",
	"You ever wonder why Strength costs more than Wisdom? I don’t. I just ring it up.",
	"I once watched someone spend three hours choosing their stats... then trip over a root in the tutorial zone.",
	"Just know whatever you pick, fate will find a way to mock you. It always does.",
	"You’re being very methodical. I respect that. Not enough to help, but I respect it.",
	"I could tell you what the optimal build is... but where's the fun in that?",
	"You think you're the first one to try a full Dexterity build? Ha. Good luck with wind.",
	"Every point tells a story. Most of them end with mild regret.",
	"Don't worry, the stats you pick now only define your entire experience. No pressure.",
	"Reminds me of the time I tried point buy with a mimic. It didn't go well.",
	"I'd warn you about overspecializing, but hey, live dangerously.",
	"Ever allocate points while cursed? You’re not, are you? ...Right?",
	"Try not to stare at the numbers too long. They start whispering back.",
	"Your hands tremble with power... or indecision. It's hard to tell.",
];

export const shopKeeperResults = [
	"Well, well. A build with consequences. I respect that.",
	"Sealed in fate, scribbled in ink, and entirely your problem now.",
	"Hope you're happy with those choices... because they’re very permanent. Probably.",
	"Mmm. A stat spread only a mother could love.",
	"Ah, bold and mildly concerning. My favorite combination.",
	"Locked in? Wonderful. I love the sound of irreversible decisions.",
	"You done? Good. Now we find out what the universe thinks of you.",
	"Excellent. Now let’s pretend you knew what you were doing.",
	"Stats confirmed. The prophecy trembles.",
	"Well, those are numbers. Let’s hope they add up to survival.",
	"Choices made, regrets pending.",
	"Looks like someone’s ready to face destiny... or at least trip into it.",
	"Ah. Another custom blend of ambition and overconfidence.",
	"Finalized? Brave. Foolish, maybe, but brave.",
	"I'll file these under 'optimistic'. Good luck out there.",
	"Done already? Huh. Bold speed for a delicate operation.",
	"Great. Now if you explode later, it’s not on me.",
	"And with that, your fate is caffeinated and ready to go.",
	"The ink’s still wet, but I’m sure it’ll hold... mostly.",
	"A curious arrangement of numbers. I look forward to seeing it fail or flourish.",
	"The final numbers fall into place... like teeth in a hungry smile.",
	"Ah, the pattern is complete. I hope it doesn’t summon anything.",
	"And so, the shape of you is written. Odd shape, that.",
	"Very well. The pact is sealed. No swapsies.",
	"The tally is done. The stars blink knowingly.",
	"Choices laid bare... may they carry you farther than they carried me.",
	"Interesting. The last one who chose this arrangement disappeared. Probably unrelated.",
	"Hm. Your fate stirs. Or maybe that’s the broom again.",
	"The numbers hum. That’s either approval or indigestion.",
	"It is written. Poorly, but it’s written.",
	"A whisper moves through the shelves... it seems they approve.",
	"Ah. The ritual is complete. The consequences... not yet.",
	"Good. I can almost smell the narrative tension.",
	"You've chosen. The weight of potential presses down like an old quilt.",
	"Curious spread. The bones agree. Some of them.",
	"It is done. The runes groan, but they’ll manage.",
	"Your form is fixed... for now. Reality’s flexible, but not *that* flexible.",
	"I'll archive this under 'Experimental.' You’ll do fine. Probably.",
	"So be it. The ledger accepts your sum. Let’s hope you can carry it.",
	"I was about to say nice rolls, but you just whipped out a wallet.",
	"I was about to say nice rolls, but you just whipped out a wallet.",
	"Ah, the sound of coins buying destiny. Truly magical.",
	"Point by point, your legend is... financially optimized.",
	"Nothing says heroic journey like careful budgeting.",
	"Well, that’s one way to build character. Literally.",
	"Buying power? Bold. Capitalism always wins.",
	"Just once, I’d like someone to embrace chaos. But nooo, balance.",
	"And with that, your build is complete. Receipts available upon request.",
	"Optimized and monetized. You’ll go far, probably too far.",
	"Mm. Efficient. Uninspired. But efficient.",
	"A solid build. Would've preferred a little drama, but fine.",
	"All wrapped up. Now leave a review... or a tip.",
	"Mind leaving five stars and a blood offering? Or just the stars?",
	"If you're satisfied with your stats, please scream loudly into the mirror. It's how we count reviews.",
	"Thanks for shopping Jerry’s Soul Forge & Stat Emporium™. No refunds.",
	"Was it everything you dreamed? Please rate your regret on a scale of 1 to 6.",
	"Enjoy your stats. I’ll be muttering about them for the next hour regardless.",
	"All done? Don’t forget to tell your friends about Jerry. Or don’t. It’s quieter that way.",
	"Glad I could help shape your fate. If anything explodes, it wasn’t me.",
	"I’ve seen worse. And I’ve sold worse. So you’re in good shape.",
	"...Are we done? Great. I’m going back to sleep now.",
	"Cool. Stats set. Please don’t need anything else.",
	"Wonderful. Now I can resume my eternal nap.",
	"Another hero forged, another nap delayed.",
	"Finally. Do you know how hard it is to yawn silently?",
	"Okay, you're done. Now leave me to my lukewarm tea and existential dread.",
	"Finished? Great. Wake me when destiny collapses.",
	"Ah, the thrill of paperwork and point allocation. Riveting.",
	"Let me know if you need anything. Actually, don’t.",
	"Cool, cool... I’ll just be lying face-down behind the counter now.",
	"Another masterpiece built... with math. Fascinating.",
	"You're all set. I'm going to stare into the wall for a bit.",
	"Great build. Truly. I’m weeping with joy on the inside.",
	"Your stats are fine. Can I go back to pretending to dust things now?",
	"Ah yes, the joy of customer service. Please leave me alone.",
	"Alright, destiny is officially priced and packaged. I need a nap.",
	"You’re done? Good. I’ve got 37 more years of slouching to catch up on.",
	"Thank you for choosing Jerry’s. Now please stop choosing Jerry’s.",
	"And with that... I drift back into the void of minor apathy.",
	"Another adventurer walks out... and I remain. Forever. Here.",
];
