export const standardArraySentences = [
	`Ah, the hero chooses fate over fortune... a bold, or lazy choice.`,
	`The runes remain untouched... simplicity, the true magic.`,
	`You did not roll... the gods shrug in mild indifference.`,
	`Destiny pre-written is still destiny... or so the sages claim.`,
	`Skipping the chaos of dice? Truly, the mark of a stable mind.`,
	`No dice rolled... somewhere, a goblin yawns.`,
	`The dice remain silent... the fates mutter among themselves.`,
	`Wow. Living life on the edge, huh?`,
	`Too cool to roll dice, are we?`,
	`Not even gonna try for better stats? Respect.`,
	`Skipping the fun part? That's one way to play.`,
	`Some heroes roll dice... others, click "Next".`,
	`Who needs suspense when you've got mediocrity?`,
	`The dice are crying. They miss you.`,
	`No rolling? Bold strategy, Cotton.`,
	`Balance over chaos... a rare trait in adventurers.`,
	`Sometimes, the path ahead requires no randomness.`,
	`A silent dice is still a choice made.`,
	`You've accepted the stats as written... orderly, efficient, emotionless.`,
	`The die uncast, your story remains steady... for now.`,
	`Even destiny respects a decisive click.`,
	`Pre-defined stats? Truly, the IKEA of character creation.`,
	`Wow, thrilling... you clicked the "I fear chaos" button.`,
	`No dice? No drama? No personality?`,
	`A true adventurer... of mild convenience.`,
	`Preset stats? Let me guess, you also sort your inventory alphabetically.`,
	`Living life with safe, predictable numbers... edgy.`,
	`You skipped the dice roll? What a wild rebel.`,
	`Some seek glory. You chose "good enough".`,
	`Why tempt fate when you can bore it instead?`,
	`A strong choice... if your dream is to be forgettable.`,
	`Sure, go ahead. Let Excel choose your destiny.`,
	`Brave of you to opt out of fun.`,
	`Not even a single chaotic roll? Cowardice has never looked so well-organized.`,
	`Using the preset stats, huh? Bet you sip room-temperature soup.`,
	`Bold move, skipping all potential for story or disaster.`,
	`You chose order over excitement. Your god must be an accountant.`,
	`Stat spread: legally compliant, emotionally void.`,
	`Didn't even flirt with randomness... scandalous.`,
	`Fate was ready to dance, but you stayed seated.`,
	`I see you've picked the "I'm here to follow the rules" route.`,
	`A truly efficient decision... and an unforgettable beige memory.`,
	`Preset stats? Adventuring on easy mode, emotionally.`,
	`The dice are offended, but too exhausted to care.`,
	`Who needs thrills when you've got "functionally acceptable"?`,
	`You skipped chaos... and accidentally chose comedy.`,
	`Imagine skipping dice and still not being optimal. Incredible.`,
	`Truly the "white bread with no crusts" of choices.`,
	`No rolls, no risks, no regrets... just quiet sighs.`,
	`You've got the same energy as a tutorial NPC.`,
	`Preset stats? Guess you like your destiny pre-chewed.`,
	`The stars foretold a hero... but not this one.`,
	`Ah yes, the chosen one... chosen to skip rolling.`,
	`Long ago it was written... in fine print, beneath the fun part.`,
	`The prophecy said, "they shall roll the dice"... and yet, here we are.`,
	`Even the runes are confused by your lack of ambition.`,
	`A wizard once whispered, "Let fate decide"... but you weren't listening.`,
	`The scrolls are silent... probably out of disappointment.`,
	`You defied destiny... and picked the safe option.`,
	`The ancient stones have stopped glowing. They're sulking.`,
	`I peered into the future and saw... mild stats and no drama.`,
	`Your aura reads as "lukewarm compliance".`,
	`The oracles weep, but only a little. They expected this.`,
	`The sacred dice remain untouched... like your potential.`,
	`Legends spoke of a great choice. They did not mean this.`,
	`The cosmos had plans, but you had presets.`,
	`In the great hall of fate, your name is listed under "eh".`,
	`A wise sage once said, "Let chaos shape the soul"... you clicked "Skip".`,
	`Even the ancient dragons are yawning at this decision.`,
	`Your destiny was rolled... but you didn't show up.`,
	`The crystal ball just shrugged.`,
	`You treated fate like a boring spreadsheet.`,
	`Your stats are so bland, even the monsters nap.`,
	`Rolling dice? No thanks, I'll just pretend to care.`,
	`You skipped the gamble, but lost the thrill.`,
	`Congratulations! You've unlocked the "safe but dull" achievement.`,
	`Fate's waiting on you... but it's taking a coffee break.`,
	`No rolls, no fun, just a long walk through the tutorial.`,
	`Your character's luck? Somewhere between "meh" and "why bother?"`,
];
