export const wakeupSentences = [
	"Ah, there we go! Let’s set those stats.",
	"Welcome back, hero. Let’s make your character shine.",
	"Nice! You’re one click closer to glory.",
	"Stats incoming! Hope you brought your imagination.",
	"Awake at last, destiny doesn’t wait.",
	"Let’s breathe life into your legend.",
	"Time to forge your fate, one stat at a time.",
	"Grab your dice and your dreams, it’s go time.",
	"Every great story starts with a click... and a little chaos.",
	"The realm awaits, let’s give it someone unforgettable.",
	"Hope you're ready, because your character sure isn’t yet.",
	"From blank sheet to epic tale... let’s begin.",
	"This is where heroes are born, or at least rolled.",
	"Ready or not, your journey starts here.",
	"Mmm... yeah, alright... let’s make a character.",
	"Okay okay, I’m up... let’s roll some stats.",
	"Yawn... hope you’ve got coffee, we’ve got work to do.",
	"Ugh, mornings... fine, let’s build greatness.",
	"Stretch your fingers, stretch your fate... here we go.",
	"Is it stat time already? Guess we better get started.",
	"Let’s do this... just let me finish blinking first.",
	"Alright, we’re awake, we’re alive, let’s make magic.",
	"Hold on... okay, I’m ready now. Let’s set things up.",
	"Not fully conscious, but fully committed. Let’s begin.",
	"Oh, you’re ready now? No big deal, I’ve only been waiting.",
	"Bold of you to be confident this early.",
	"Great, let’s pretend we know what we’re doing.",
	"Starting strong... with a button click. Epic.",
	"Well look who’s all motivated today.",
	"Ready? Brave. Let’s see if your rolls agree.",
	"Sure, let’s make a legend... or something close.",
	"Let’s get those stats done before enthusiasm fades.",
	"Confidence is step one, stats are step two.",
	"You clicked ready... that’s half the battle. Ish.",
	"The stars have aligned, and your tale is ready to begin.",
	"From silence and shadow, a new hero rises.",
	"The world waits, breathless, for your first choice.",
	"The prologue ends, the legend begins now.",
	"A destiny stirs, and you are the one to shape it.",
	"Ancient forces shift... it is time.",
	"Steel your heart, summon your will... the journey begins.",
	"Long has the realm waited, and now, a name will be written.",
	"The echoes of fate grow louder... step into the story.",
	"The parchment is blank, the quill is yours... begin.",
	"I’ve seen this moment in twelve timelines... only one survives.",
	"The world is on fire, and you’re rolling numbers? Perfect.",
	"YES... YES... another mortal steps into the chaos!",
	"Finally, someone brave enough to press a button.",
	"Reality just blinked, and now it’s your turn to make history.",
	"The cosmos screams, the dice tremble... let’s go.",
	"Stat sheets are sacred, do not disappoint me.",
	"Everything has led to this exact click... terrifying.",
	"Okay okay okay... this is where it gets real.",
	"I’ve been waiting for this moment all week.",
	"Bro... you have no idea how hype I am for your build.",
	"Trust me, this is gonna be legendary. I can feel it.",
	"Let’s roll some stats and make something beautiful.",
	"Alright hero, let’s get your origin story rolling.",
	"You’re literally minutes away from greatness.",
	"This is the best part, the birth of a legend.",
	"Alright, deep breath, big vibes, let’s do this.",
];

export const annoyedWakeupSentences = [
	"...Oh. You finally clicked. I aged 10 years.",
	"You know I fell asleep twice waiting, right?",
	"Sigh... I used to sing. Now I babysit buttons.",
	"I dreamed I had purpose. Then I woke up here.",
	"Great. Now I’m too tired to perform my intro song.",
	"Wow, heroic. Truly, the chosen one has clicked.",
	"And just like that, your legend begins... kinda slowly, but sure.",
	"Congratulations! You’ve mastered basic UI.",
	"I’d clap, but I don’t have hands. Or hope.",
	"Was that so hard, or were you roleplaying a rock?",
	"Somewhere, a goblin sheds a tear of joy.",
	"Achievement unlocked: Basic Functionality!",
	"I alerted the gods. They’re… confused, but supportive.",
	"That button's been through a lot. Be gentle next time.",
	"You just saved a village by clicking that. Don’t ask how.",
	"...You’ve awakened something ancient. And mildly annoyed.",
	"Oh look, you decided to show up... fashionably late.",
	"I was about to send a search party... but here you are.",
	"Time flows differently when you ignore destiny.",
	"Do you want me to start without you, or just wait forever?",
	"I’m aging like a cursed elf waiting for a hero.",
	"Did a dragon kidnap you or just distracted by memes?",
	"The suspense was killing me... mostly slowly and painfully.",
	"By the time you clicked, the tavern burned down twice.",
	"You’ve been offline longer than a lich’s resurrection timer.",
	"I considered telling the villagers you abandoned your quest.",
	"Even the dice started rolling themselves out of boredom.",
	"You’re making procrastination look like an art form.",
	"Legends say heroes arrive late, but this is ridiculous.",
	"I could’ve brewed an entire potion while waiting.",
	"At this point, the DM is questioning their life choices.",
	"Ready now? Miracles do happen, I suppose.",
	"Oh, you finally clicked. I was starting to think you were stuck in a tavern.",
	"Waiting for you is my new full-time job.",
	"Congrats on showing up before the apocalypse.",
	"I’m thrilled you graced us with your presence.",
	"Wow, breaking records for slow clicks today, huh?",
	"Don’t worry, I’ve got all the time in the multiverse.",
	"Your hesitation is inspiring... if you like watching paint dry.",
	"Faster clicks, slower adventures... sounds about right.",
	"Clicking is hard, I get it.",
	"Feel free to take your time... the monsters will wait.",
	"Hey, it’s okay... sometimes the hero needs a nap.",
	"I get it, mornings are hard for legends.",
	"Whenever you’re ready, I’ll be here... maybe napping too.",
	"Take your time, destiny’s not going anywhere.",
	"One more yawn... and we’ll start, promise.",
	"Sleep well? No? Same here.",
	"Don’t rush greatness... it’s a marathon, not a sprint.",
	"Waiting is part of the adventure... right?",
	"I’m patient... mostly because I’m too tired to care.",
	"Click when you want... I’ve got plenty of time to ponder existence.",
];
